#!/bin/bash

psql --username "$POSTGRES_USER" --command "
	-- Create Roles
	CREATE ROLE ZFGCADMIN
	WITH
		NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION NOBYPASSRLS CONNECTION
	LIMIT
		-1;

	COMMENT ON ROLE ZFGCADMIN IS 'Admin users.';

	-- Create User
	CREATE ROLE $ZFGBB_USER
	WITH
		LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION NOBYPASSRLS CONNECTION
	LIMIT
		-1 PASSWORD '$ZFGBB_USER_PASSWORD';

	GRANT ZFGCADMIN TO $ZFGBB_USER
	WITH
		ADMIN OPTION;

	COMMENT ON ROLE $ZFGBB_USER IS 'Default ZFGBB User.';
"

psql --username "$POSTGRES_USER" --command  "
	-- Create Database 
	CREATE DATABASE $ZFGBB_DATABASE
		WITH
		OWNER = $ZFGBB_USER;
	GRANT ALL ON DATABASE $ZFGBB_DATABASE TO zfgcadmin WITH GRANT OPTION;
	GRANT ALL ON DATABASE $ZFGBB_DATABASE TO $ZFGBB_USER;
"

psql --username "$POSTGRES_USER" --dbname "$ZFGBB_DATABASE" --command "
	CREATE SCHEMA IF NOT EXISTS ZFGBB AUTHORIZATION $ZFGBB_USER;
	COMMENT ON SCHEMA ZFGBB IS 'ZFGBB Schema.';

	GRANT ALL ON SCHEMA ZFGBB TO $ZFGBB_USER;
	GRANT ALL ON SCHEMA ZFGBB TO ZFGCADMIN WITH GRANT OPTION;

	ALTER DEFAULT PRIVILEGES IN SCHEMA ZFGBB GRANT ALL ON TABLES TO ZFGCADMIN;
	GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ZFGBB TO ZFGCADMIN;
"

psql --username "$POSTGRES_USER" --dbname "$ZFGBB_DATABASE" -a -f ./2-provision-database 