services:
  postgresql:
    build:
      context: .
      dockerfile: Dockerfile
      target: database
    container_name: zfgcbb_postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=zfgcbb
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready" ,"-d", "zfgcbb"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  

  zfgcbb:
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
    ports:
      - "8080:8080"
    volumes:
      - logs:/usr/src/app/logs
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://zfgcbb_postgresql:5432/zfgcbb
      - SPRING_DATASOURCE_USERNAME=postgres   
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    depends_on:
      - postgresql

volumes:
  data:
  logs:
