services:
  postgresql:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  zfgcbb:
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
    ports:
      - "8080:8080"
    volumes:
      - logs:/usr/src/app/logs
    environment:
      - JAVA_OPTS=-Xms128m -Xmx512m
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/zfgcbb?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_USERNAME=postgres   
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
    depends_on:
      - postgresql

volumes:
  data:
  logs:
