package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.AllMessagesInThreadViewDbo;
import com.zfgc.zfgbb.dbo.AllMessagesInThreadViewDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AllMessagesInThreadViewDboMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.all_messages_in_thread_view
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    long countByExample(AllMessagesInThreadViewDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.all_messages_in_thread_view
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    int deleteByExample(AllMessagesInThreadViewDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.all_messages_in_thread_view
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    int insert(AllMessagesInThreadViewDbo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.all_messages_in_thread_view
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    int insertSelective(AllMessagesInThreadViewDbo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.all_messages_in_thread_view
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    List<AllMessagesInThreadViewDbo> selectByExample(AllMessagesInThreadViewDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.all_messages_in_thread_view
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    int updateByExampleSelective(@Param("row") AllMessagesInThreadViewDbo row, @Param("example") AllMessagesInThreadViewDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.all_messages_in_thread_view
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    int updateByExample(@Param("row") AllMessagesInThreadViewDbo row, @Param("example") AllMessagesInThreadViewDboExample example);
}