package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.AttributeDataTypeDbo;
import com.zfgc.zfgbb.dbo.AttributeDataTypeDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttributeDataTypeDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.attribute_data_type
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	long countByExample(AttributeDataTypeDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.attribute_data_type
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	int deleteByExample(AttributeDataTypeDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.attribute_data_type
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	int deleteByPrimaryKey(Integer attributeDataTypeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.attribute_data_type
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	int insert(AttributeDataTypeDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.attribute_data_type
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	int insertSelective(AttributeDataTypeDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.attribute_data_type
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	List<AttributeDataTypeDbo> selectByExample(AttributeDataTypeDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.attribute_data_type
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	AttributeDataTypeDbo selectByPrimaryKey(Integer attributeDataTypeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.attribute_data_type
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	int updateByExampleSelective(@Param("record") AttributeDataTypeDbo record,
			@Param("example") AttributeDataTypeDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.attribute_data_type
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	int updateByExample(@Param("record") AttributeDataTypeDbo record,
			@Param("example") AttributeDataTypeDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.attribute_data_type
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	int updateByPrimaryKeySelective(AttributeDataTypeDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.attribute_data_type
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	int updateByPrimaryKey(AttributeDataTypeDbo record);
}