package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.zfgbb.AttributeDataTypeDbo;
import com.zfgc.zfgbb.dbo.zfgbb.AttributeDataTypeDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttributeDataTypeDboMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.attribute_data_type
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    long countByExample(AttributeDataTypeDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.attribute_data_type
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    int deleteByExample(AttributeDataTypeDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.attribute_data_type
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    int deleteByPrimaryKey(Integer attributeDataTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.attribute_data_type
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    int insert(AttributeDataTypeDbo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.attribute_data_type
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    int insertSelective(AttributeDataTypeDbo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.attribute_data_type
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    List<AttributeDataTypeDbo> selectByExample(AttributeDataTypeDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.attribute_data_type
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    AttributeDataTypeDbo selectByPrimaryKey(Integer attributeDataTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.attribute_data_type
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    int updateByExampleSelective(@Param("record") AttributeDataTypeDbo record, @Param("example") AttributeDataTypeDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.attribute_data_type
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    int updateByExample(@Param("record") AttributeDataTypeDbo record, @Param("example") AttributeDataTypeDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.attribute_data_type
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    int updateByPrimaryKeySelective(AttributeDataTypeDbo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.attribute_data_type
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    int updateByPrimaryKey(AttributeDataTypeDbo record);
}