package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.AvatarDbo;
import com.zfgc.zfgbb.dbo.AvatarDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AvatarDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.avatar
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	long countByExample(AvatarDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.avatar
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	int deleteByExample(AvatarDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.avatar
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	int deleteByPrimaryKey(Integer avatarId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.avatar
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	int insert(AvatarDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.avatar
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	int insertSelective(AvatarDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.avatar
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	List<AvatarDbo> selectByExample(AvatarDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.avatar
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	AvatarDbo selectByPrimaryKey(Integer avatarId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.avatar
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	int updateByExampleSelective(@Param("record") AvatarDbo record, @Param("example") AvatarDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.avatar
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	int updateByExample(@Param("record") AvatarDbo record, @Param("example") AvatarDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.avatar
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	int updateByPrimaryKeySelective(AvatarDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.avatar
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	int updateByPrimaryKey(AvatarDbo record);
}