package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.BBCodeAttributeModeDbo;
import com.zfgc.zfgbb.dbo.BBCodeAttributeModeDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BBCodeAttributeModeDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.bb_code_attribute_mode
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	long countByExample(BBCodeAttributeModeDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.bb_code_attribute_mode
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int deleteByExample(BBCodeAttributeModeDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.bb_code_attribute_mode
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int deleteByPrimaryKey(Integer bbCodeAttributeModeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.bb_code_attribute_mode
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int insert(BBCodeAttributeModeDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.bb_code_attribute_mode
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int insertSelective(BBCodeAttributeModeDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.bb_code_attribute_mode
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	List<BBCodeAttributeModeDbo> selectByExample(BBCodeAttributeModeDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.bb_code_attribute_mode
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	BBCodeAttributeModeDbo selectByPrimaryKey(Integer bbCodeAttributeModeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.bb_code_attribute_mode
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int updateByExampleSelective(@Param("record") BBCodeAttributeModeDbo record,
			@Param("example") BBCodeAttributeModeDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.bb_code_attribute_mode
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int updateByExample(@Param("record") BBCodeAttributeModeDbo record,
			@Param("example") BBCodeAttributeModeDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.bb_code_attribute_mode
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int updateByPrimaryKeySelective(BBCodeAttributeModeDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.bb_code_attribute_mode
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int updateByPrimaryKey(BBCodeAttributeModeDbo record);
}