package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.BBCodeAttributeDbo;
import com.zfgc.zfgbb.dbo.BBCodeAttributeDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BBCodeAttributeDboMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.bb_code_attribute
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    long countByExample(BBCodeAttributeDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.bb_code_attribute
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    int deleteByExample(BBCodeAttributeDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.bb_code_attribute
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    int deleteByPrimaryKey(Integer bbCodeAttributeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.bb_code_attribute
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    int insert(BBCodeAttributeDbo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.bb_code_attribute
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    int insertSelective(BBCodeAttributeDbo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.bb_code_attribute
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    List<BBCodeAttributeDbo> selectByExample(BBCodeAttributeDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.bb_code_attribute
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    BBCodeAttributeDbo selectByPrimaryKey(Integer bbCodeAttributeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.bb_code_attribute
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    int updateByExampleSelective(@Param("record") BBCodeAttributeDbo record, @Param("example") BBCodeAttributeDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.bb_code_attribute
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    int updateByExample(@Param("record") BBCodeAttributeDbo record, @Param("example") BBCodeAttributeDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.bb_code_attribute
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    int updateByPrimaryKeySelective(BBCodeAttributeDbo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.bb_code_attribute
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    int updateByPrimaryKey(BBCodeAttributeDbo record);
}