package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.BBCodeConfigDbo;
import com.zfgc.zfgbb.dbo.BBCodeConfigDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BBCodeConfigDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.bb_code_config
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	long countByExample(BBCodeConfigDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.bb_code_config
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int deleteByExample(BBCodeConfigDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.bb_code_config
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int deleteByPrimaryKey(Integer bbCodeConfigId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.bb_code_config
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int insert(BBCodeConfigDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.bb_code_config
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int insertSelective(BBCodeConfigDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.bb_code_config
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	List<BBCodeConfigDbo> selectByExample(BBCodeConfigDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.bb_code_config
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	BBCodeConfigDbo selectByPrimaryKey(Integer bbCodeConfigId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.bb_code_config
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int updateByExampleSelective(@Param("record") BBCodeConfigDbo record,
			@Param("example") BBCodeConfigDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.bb_code_config
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int updateByExample(@Param("record") BBCodeConfigDbo record, @Param("example") BBCodeConfigDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.bb_code_config
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int updateByPrimaryKeySelective(BBCodeConfigDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.bb_code_config
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int updateByPrimaryKey(BBCodeConfigDbo record);
}