package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.BoardSummaryViewDbo;
import com.zfgc.zfgbb.dbo.BoardSummaryViewDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BoardSummaryViewDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board_summary
	 * @mbg.generated  Sun Oct 13 23:30:46 EDT 2024
	 */
	long countByExample(BoardSummaryViewDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board_summary
	 * @mbg.generated  Sun Oct 13 23:30:46 EDT 2024
	 */
	int deleteByExample(BoardSummaryViewDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board_summary
	 * @mbg.generated  Sun Oct 13 23:30:46 EDT 2024
	 */
	int insert(BoardSummaryViewDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board_summary
	 * @mbg.generated  Sun Oct 13 23:30:46 EDT 2024
	 */
	int insertSelective(BoardSummaryViewDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board_summary
	 * @mbg.generated  Sun Oct 13 23:30:46 EDT 2024
	 */
	List<BoardSummaryViewDbo> selectByExample(BoardSummaryViewDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board_summary
	 * @mbg.generated  Sun Oct 13 23:30:46 EDT 2024
	 */
	int updateByExampleSelective(@Param("record") BoardSummaryViewDbo record,
			@Param("example") BoardSummaryViewDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board_summary
	 * @mbg.generated  Sun Oct 13 23:30:46 EDT 2024
	 */
	int updateByExample(@Param("record") BoardSummaryViewDbo record,
			@Param("example") BoardSummaryViewDboExample example);
}