package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.BoardSummaryViewDbo;
import com.zfgc.zfgbb.dbo.BoardSummaryViewDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BoardSummaryViewDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board_summary
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	long countByExample(BoardSummaryViewDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board_summary
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	int deleteByExample(BoardSummaryViewDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board_summary
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	int insert(BoardSummaryViewDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board_summary
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	int insertSelective(BoardSummaryViewDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board_summary
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	List<BoardSummaryViewDbo> selectByExample(BoardSummaryViewDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board_summary
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	int updateByExampleSelective(@Param("row") BoardSummaryViewDbo row,
			@Param("example") BoardSummaryViewDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board_summary
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	int updateByExample(@Param("row") BoardSummaryViewDbo row, @Param("example") BoardSummaryViewDboExample example);
}