package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.BoardPermissionViewDbo;
import com.zfgc.zfgbb.dbo.BoardPermissionViewDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BoardPermissionViewDboMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.board_permission_view
     *
     * @mbg.generated Sun Feb 27 09:04:00 EST 2022
     */
    long countByExample(BoardPermissionViewDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.board_permission_view
     *
     * @mbg.generated Sun Feb 27 09:04:00 EST 2022
     */
    int deleteByExample(BoardPermissionViewDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.board_permission_view
     *
     * @mbg.generated Sun Feb 27 09:04:00 EST 2022
     */
    int insert(BoardPermissionViewDbo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.board_permission_view
     *
     * @mbg.generated Sun Feb 27 09:04:00 EST 2022
     */
    int insertSelective(BoardPermissionViewDbo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.board_permission_view
     *
     * @mbg.generated Sun Feb 27 09:04:00 EST 2022
     */
    List<BoardPermissionViewDbo> selectByExample(BoardPermissionViewDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.board_permission_view
     *
     * @mbg.generated Sun Feb 27 09:04:00 EST 2022
     */
    int updateByExampleSelective(@Param("record") BoardPermissionViewDbo record, @Param("example") BoardPermissionViewDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.board_permission_view
     *
     * @mbg.generated Sun Feb 27 09:04:00 EST 2022
     */
    int updateByExample(@Param("record") BoardPermissionViewDbo record, @Param("example") BoardPermissionViewDboExample example);
}