package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.BoardDbo;
import com.zfgc.zfgbb.dbo.BoardDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BoardDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board
	 * @mbg.generated  Wed Feb 23 22:16:25 EST 2022
	 */
	long countByExample(BoardDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board
	 * @mbg.generated  Wed Feb 23 22:16:25 EST 2022
	 */
	int deleteByExample(BoardDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board
	 * @mbg.generated  Wed Feb 23 22:16:25 EST 2022
	 */
	int deleteByPrimaryKey(Integer boardId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board
	 * @mbg.generated  Wed Feb 23 22:16:25 EST 2022
	 */
	int insert(BoardDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board
	 * @mbg.generated  Wed Feb 23 22:16:25 EST 2022
	 */
	int insertSelective(BoardDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board
	 * @mbg.generated  Wed Feb 23 22:16:25 EST 2022
	 */
	List<BoardDbo> selectByExample(BoardDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board
	 * @mbg.generated  Wed Feb 23 22:16:25 EST 2022
	 */
	BoardDbo selectByPrimaryKey(Integer boardId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board
	 * @mbg.generated  Wed Feb 23 22:16:25 EST 2022
	 */
	int updateByExampleSelective(@Param("record") BoardDbo record, @Param("example") BoardDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board
	 * @mbg.generated  Wed Feb 23 22:16:25 EST 2022
	 */
	int updateByExample(@Param("record") BoardDbo record, @Param("example") BoardDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board
	 * @mbg.generated  Wed Feb 23 22:16:25 EST 2022
	 */
	int updateByPrimaryKeySelective(BoardDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.board
	 * @mbg.generated  Wed Feb 23 22:16:25 EST 2022
	 */
	int updateByPrimaryKey(BoardDbo record);
}