package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.CategoryDbo;
import com.zfgc.zfgbb.dbo.CategoryDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CategoryDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.category
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	long countByExample(CategoryDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.category
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int deleteByExample(CategoryDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.category
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int deleteByPrimaryKey(Integer categoryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.category
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int insert(CategoryDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.category
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int insertSelective(CategoryDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.category
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	List<CategoryDbo> selectByExample(CategoryDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.category
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	CategoryDbo selectByPrimaryKey(Integer categoryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.category
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int updateByExampleSelective(@Param("record") CategoryDbo record, @Param("example") CategoryDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.category
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int updateByExample(@Param("record") CategoryDbo record, @Param("example") CategoryDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.category
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int updateByPrimaryKeySelective(CategoryDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.category
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int updateByPrimaryKey(CategoryDbo record);
}