package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.ChildBoardViewDbo;
import com.zfgc.zfgbb.dbo.ChildBoardViewDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChildBoardViewDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.child_board_view
	 * @mbg.generated  Mon Oct 14 23:44:38 EDT 2024
	 */
	long countByExample(ChildBoardViewDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.child_board_view
	 * @mbg.generated  Mon Oct 14 23:44:38 EDT 2024
	 */
	int deleteByExample(ChildBoardViewDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.child_board_view
	 * @mbg.generated  Mon Oct 14 23:44:38 EDT 2024
	 */
	int insert(ChildBoardViewDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.child_board_view
	 * @mbg.generated  Mon Oct 14 23:44:38 EDT 2024
	 */
	int insertSelective(ChildBoardViewDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.child_board_view
	 * @mbg.generated  Mon Oct 14 23:44:38 EDT 2024
	 */
	List<ChildBoardViewDbo> selectByExample(ChildBoardViewDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.child_board_view
	 * @mbg.generated  Mon Oct 14 23:44:38 EDT 2024
	 */
	int updateByExampleSelective(@Param("record") ChildBoardViewDbo record,
			@Param("example") ChildBoardViewDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.child_board_view
	 * @mbg.generated  Mon Oct 14 23:44:38 EDT 2024
	 */
	int updateByExample(@Param("record") ChildBoardViewDbo record, @Param("example") ChildBoardViewDboExample example);
}