package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.CurrentMessageDbo;
import com.zfgc.zfgbb.dbo.CurrentMessageDboExample;
import com.zfgc.zfgbb.dbo.MessageDbo;
import com.zfgc.zfgbb.dbo.MessageDboExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CurrentMessageDboMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.current_message_view
	 * @mbg.generated  Wed Aug 21 23:16:54 EDT 2024
	 */
	long countByExample(CurrentMessageDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.current_message_view
	 * @mbg.generated  Wed Aug 21 23:16:54 EDT 2024
	 */
	int deleteByExample(CurrentMessageDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.current_message_view
	 * @mbg.generated  Wed Aug 21 23:16:54 EDT 2024
	 */
	int insert(CurrentMessageDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.current_message_view
	 * @mbg.generated  Wed Aug 21 23:16:54 EDT 2024
	 */
	int insertSelective(CurrentMessageDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.current_message_view
	 * @mbg.generated  Wed Aug 21 23:16:54 EDT 2024
	 */
	List<CurrentMessageDbo> selectByExample(CurrentMessageDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.current_message_view
	 * @mbg.generated  Wed Aug 21 23:16:54 EDT 2024
	 */
	int updateByExampleSelective(@Param("record") CurrentMessageDbo record,
			@Param("example") CurrentMessageDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.current_message_view
	 * @mbg.generated  Wed Aug 21 23:16:54 EDT 2024
	 */
	int updateByExample(@Param("record") CurrentMessageDbo record, @Param("example") CurrentMessageDboExample example);

	List<CurrentMessageDbo> selectByExampleWithLimit(@Param("example") CurrentMessageDboExample example, @Param("start") Integer start, @Param("total") Integer total);
}