package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.EmailAddressDbo;
import com.zfgc.zfgbb.dbo.EmailAddressDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmailAddressDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	long countByExample(EmailAddressDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int deleteByExample(EmailAddressDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int deleteByPrimaryKey(Integer emailAddressId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int insert(EmailAddressDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int insertSelective(EmailAddressDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	List<EmailAddressDbo> selectByExample(EmailAddressDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	EmailAddressDbo selectByPrimaryKey(Integer emailAddressId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int updateByExampleSelective(@Param("record") EmailAddressDbo record,
			@Param("example") EmailAddressDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int updateByExample(@Param("record") EmailAddressDbo record, @Param("example") EmailAddressDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int updateByPrimaryKeySelective(EmailAddressDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int updateByPrimaryKey(EmailAddressDbo record);
}