package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.FileAttachmentDbo;
import com.zfgc.zfgbb.dbo.FileAttachmentDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileAttachmentDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.file_attachments
	 * @mbg.generated  Sat Jul 05 18:58:18 EDT 2025
	 */
	long countByExample(FileAttachmentDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.file_attachments
	 * @mbg.generated  Sat Jul 05 18:58:18 EDT 2025
	 */
	int deleteByExample(FileAttachmentDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.file_attachments
	 * @mbg.generated  Sat Jul 05 18:58:18 EDT 2025
	 */
	int deleteByPrimaryKey(Integer fileAttachmentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.file_attachments
	 * @mbg.generated  Sat Jul 05 18:58:18 EDT 2025
	 */
	int insert(FileAttachmentDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.file_attachments
	 * @mbg.generated  Sat Jul 05 18:58:18 EDT 2025
	 */
	int insertSelective(FileAttachmentDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.file_attachments
	 * @mbg.generated  Sat Jul 05 18:58:18 EDT 2025
	 */
	List<FileAttachmentDbo> selectByExample(FileAttachmentDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.file_attachments
	 * @mbg.generated  Sat Jul 05 18:58:18 EDT 2025
	 */
	FileAttachmentDbo selectByPrimaryKey(Integer fileAttachmentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.file_attachments
	 * @mbg.generated  Sat Jul 05 18:58:18 EDT 2025
	 */
	int updateByExampleSelective(@Param("row") FileAttachmentDbo row,
			@Param("example") FileAttachmentDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.file_attachments
	 * @mbg.generated  Sat Jul 05 18:58:18 EDT 2025
	 */
	int updateByExample(@Param("row") FileAttachmentDbo row, @Param("example") FileAttachmentDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.file_attachments
	 * @mbg.generated  Sat Jul 05 18:58:18 EDT 2025
	 */
	int updateByPrimaryKeySelective(FileAttachmentDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.file_attachments
	 * @mbg.generated  Sat Jul 05 18:58:18 EDT 2025
	 */
	int updateByPrimaryKey(FileAttachmentDbo row);
}