package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.FileAttachmentDbo;
import com.zfgc.zfgbb.dbo.FileAttachmentDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileAttachmentDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.file_attachments
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	long countByExample(FileAttachmentDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.file_attachments
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	int deleteByExample(FileAttachmentDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.file_attachments
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	int deleteByPrimaryKey(Integer fileAttachmentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.file_attachments
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	int insert(FileAttachmentDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.file_attachments
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	int insertSelective(FileAttachmentDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.file_attachments
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	List<FileAttachmentDbo> selectByExample(FileAttachmentDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.file_attachments
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	FileAttachmentDbo selectByPrimaryKey(Integer fileAttachmentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.file_attachments
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	int updateByExampleSelective(@Param("record") FileAttachmentDbo record,
			@Param("example") FileAttachmentDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.file_attachments
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	int updateByExample(@Param("record") FileAttachmentDbo record, @Param("example") FileAttachmentDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.file_attachments
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	int updateByPrimaryKeySelective(FileAttachmentDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.file_attachments
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	int updateByPrimaryKey(FileAttachmentDbo record);
}