package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.IpAddressDbo;
import com.zfgc.zfgbb.dbo.IpAddressDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IpAddressDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.ip_address
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	long countByExample(IpAddressDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.ip_address
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	int deleteByExample(IpAddressDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.ip_address
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	int deleteByPrimaryKey(Integer ipAddressId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.ip_address
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	int insert(IpAddressDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.ip_address
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	int insertSelective(IpAddressDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.ip_address
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	List<IpAddressDbo> selectByExample(IpAddressDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.ip_address
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	IpAddressDbo selectByPrimaryKey(Integer ipAddressId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.ip_address
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	int updateByExampleSelective(@Param("record") IpAddressDbo record, @Param("example") IpAddressDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.ip_address
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	int updateByExample(@Param("record") IpAddressDbo record, @Param("example") IpAddressDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.ip_address
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	int updateByPrimaryKeySelective(IpAddressDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.ip_address
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	int updateByPrimaryKey(IpAddressDbo record);
}