package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.LatestMessageInThreadViewDbo;
import com.zfgc.zfgbb.dbo.LatestMessageInThreadViewDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LatestMessageInThreadViewDboMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.latest_message_in_thread_view
     *
     * @mbg.generated Tue Oct 08 19:03:12 EDT 2024
     */
    long countByExample(LatestMessageInThreadViewDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.latest_message_in_thread_view
     *
     * @mbg.generated Tue Oct 08 19:03:12 EDT 2024
     */
    int deleteByExample(LatestMessageInThreadViewDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.latest_message_in_thread_view
     *
     * @mbg.generated Tue Oct 08 19:03:12 EDT 2024
     */
    int insert(LatestMessageInThreadViewDbo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.latest_message_in_thread_view
     *
     * @mbg.generated Tue Oct 08 19:03:12 EDT 2024
     */
    int insertSelective(LatestMessageInThreadViewDbo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.latest_message_in_thread_view
     *
     * @mbg.generated Tue Oct 08 19:03:12 EDT 2024
     */
    List<LatestMessageInThreadViewDbo> selectByExample(LatestMessageInThreadViewDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.latest_message_in_thread_view
     *
     * @mbg.generated Tue Oct 08 19:03:12 EDT 2024
     */
    int updateByExampleSelective(@Param("record") LatestMessageInThreadViewDbo record, @Param("example") LatestMessageInThreadViewDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.latest_message_in_thread_view
     *
     * @mbg.generated Tue Oct 08 19:03:12 EDT 2024
     */
    int updateByExample(@Param("record") LatestMessageInThreadViewDbo record, @Param("example") LatestMessageInThreadViewDboExample example);
}