package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.MessageDbo;
import com.zfgc.zfgbb.dbo.MessageDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessageDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message
	 * @mbg.generated  Sat Aug 03 19:44:59 EDT 2024
	 */
	long countByExample(MessageDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message
	 * @mbg.generated  Sat Aug 03 19:44:59 EDT 2024
	 */
	int deleteByExample(MessageDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message
	 * @mbg.generated  Sat Aug 03 19:44:59 EDT 2024
	 */
	int deleteByPrimaryKey(Integer messageId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message
	 * @mbg.generated  Sat Aug 03 19:44:59 EDT 2024
	 */
	int insert(MessageDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message
	 * @mbg.generated  Sat Aug 03 19:44:59 EDT 2024
	 */
	int insertSelective(MessageDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message
	 * @mbg.generated  Sat Aug 03 19:44:59 EDT 2024
	 */
	List<MessageDbo> selectByExample(MessageDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message
	 * @mbg.generated  Sat Aug 03 19:44:59 EDT 2024
	 */
	MessageDbo selectByPrimaryKey(Integer messageId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message
	 * @mbg.generated  Sat Aug 03 19:44:59 EDT 2024
	 */
	int updateByExampleSelective(@Param("record") MessageDbo record, @Param("example") MessageDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message
	 * @mbg.generated  Sat Aug 03 19:44:59 EDT 2024
	 */
	int updateByExample(@Param("record") MessageDbo record, @Param("example") MessageDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message
	 * @mbg.generated  Sat Aug 03 19:44:59 EDT 2024
	 */
	int updateByPrimaryKeySelective(MessageDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message
	 * @mbg.generated  Sat Aug 03 19:44:59 EDT 2024
	 */
	int updateByPrimaryKey(MessageDbo record);

	List<MessageDbo> selectByExampleWithLimit(@Param("example") MessageDboExample example, @Param("start") Integer start, @Param("total") Integer total);
}