package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.MessageHistoryDbo;
import com.zfgc.zfgbb.dbo.MessageHistoryDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessageHistoryDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message_history
	 * @mbg.generated  Mon Jul 08 22:45:25 EDT 2024
	 */
	long countByExample(MessageHistoryDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message_history
	 * @mbg.generated  Mon Jul 08 22:45:25 EDT 2024
	 */
	int deleteByExample(MessageHistoryDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message_history
	 * @mbg.generated  Mon Jul 08 22:45:25 EDT 2024
	 */
	int deleteByPrimaryKey(Integer messageHistoryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message_history
	 * @mbg.generated  Mon Jul 08 22:45:25 EDT 2024
	 */
	int insert(MessageHistoryDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message_history
	 * @mbg.generated  Mon Jul 08 22:45:25 EDT 2024
	 */
	int insertSelective(MessageHistoryDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message_history
	 * @mbg.generated  Mon Jul 08 22:45:25 EDT 2024
	 */
	List<MessageHistoryDbo> selectByExample(MessageHistoryDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message_history
	 * @mbg.generated  Mon Jul 08 22:45:25 EDT 2024
	 */
	MessageHistoryDbo selectByPrimaryKey(Integer messageHistoryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message_history
	 * @mbg.generated  Mon Jul 08 22:45:25 EDT 2024
	 */
	int updateByExampleSelective(@Param("record") MessageHistoryDbo record,
			@Param("example") MessageHistoryDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message_history
	 * @mbg.generated  Mon Jul 08 22:45:25 EDT 2024
	 */
	int updateByExample(@Param("record") MessageHistoryDbo record, @Param("example") MessageHistoryDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message_history
	 * @mbg.generated  Mon Jul 08 22:45:25 EDT 2024
	 */
	int updateByPrimaryKeySelective(MessageHistoryDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message_history
	 * @mbg.generated  Mon Jul 08 22:45:25 EDT 2024
	 */
	int updateByPrimaryKey(MessageHistoryDbo record);
}