package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.PollQuestionDbo;
import com.zfgc.zfgbb.dbo.PollQuestionDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PollQuestionDboMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_question
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    long countByExample(PollQuestionDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_question
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    int deleteByExample(PollQuestionDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_question
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    int deleteByPrimaryKey(Integer pollQuestionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_question
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    int insert(PollQuestionDbo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_question
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    int insertSelective(PollQuestionDbo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_question
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    List<PollQuestionDbo> selectByExample(PollQuestionDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_question
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    PollQuestionDbo selectByPrimaryKey(Integer pollQuestionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_question
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    int updateByExampleSelective(@Param("record") PollQuestionDbo record, @Param("example") PollQuestionDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_question
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    int updateByExample(@Param("record") PollQuestionDbo record, @Param("example") PollQuestionDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_question
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    int updateByPrimaryKeySelective(PollQuestionDbo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll_question
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    int updateByPrimaryKey(PollQuestionDbo record);
}