package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.PollDbo;
import com.zfgc.zfgbb.dbo.PollDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PollDboMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    long countByExample(PollDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    int deleteByExample(PollDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    int deleteByPrimaryKey(Integer pollId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    int insert(PollDbo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    int insertSelective(PollDbo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    List<PollDbo> selectByExample(PollDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    PollDbo selectByPrimaryKey(Integer pollId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    int updateByExampleSelective(@Param("record") PollDbo record, @Param("example") PollDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    int updateByExample(@Param("record") PollDbo record, @Param("example") PollDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    int updateByPrimaryKeySelective(PollDbo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.poll
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    int updateByPrimaryKey(PollDbo record);
}