package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.UserBioInfoDbo;
import com.zfgc.zfgbb.dbo.UserBioInfoDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserBioInfoDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_bio_info
	 * @mbg.generated  Tue Sep 17 22:24:36 EDT 2024
	 */
	long countByExample(UserBioInfoDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_bio_info
	 * @mbg.generated  Tue Sep 17 22:24:36 EDT 2024
	 */
	int deleteByExample(UserBioInfoDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_bio_info
	 * @mbg.generated  Tue Sep 17 22:24:36 EDT 2024
	 */
	int deleteByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_bio_info
	 * @mbg.generated  Tue Sep 17 22:24:36 EDT 2024
	 */
	int insert(UserBioInfoDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_bio_info
	 * @mbg.generated  Tue Sep 17 22:24:36 EDT 2024
	 */
	int insertSelective(UserBioInfoDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_bio_info
	 * @mbg.generated  Tue Sep 17 22:24:36 EDT 2024
	 */
	List<UserBioInfoDbo> selectByExample(UserBioInfoDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_bio_info
	 * @mbg.generated  Tue Sep 17 22:24:36 EDT 2024
	 */
	UserBioInfoDbo selectByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_bio_info
	 * @mbg.generated  Tue Sep 17 22:24:36 EDT 2024
	 */
	int updateByExampleSelective(@Param("record") UserBioInfoDbo record,
			@Param("example") UserBioInfoDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_bio_info
	 * @mbg.generated  Tue Sep 17 22:24:36 EDT 2024
	 */
	int updateByExample(@Param("record") UserBioInfoDbo record, @Param("example") UserBioInfoDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_bio_info
	 * @mbg.generated  Tue Sep 17 22:24:36 EDT 2024
	 */
	int updateByPrimaryKeySelective(UserBioInfoDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_bio_info
	 * @mbg.generated  Tue Sep 17 22:24:36 EDT 2024
	 */
	int updateByPrimaryKey(UserBioInfoDbo record);
}