package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.zfgbb.UserPermissionViewDbo;
import com.zfgc.zfgbb.dbo.zfgbb.UserPermissionViewDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPermissionViewDboMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.user_permission_view
     *
     * @mbg.generated Sat Feb 26 19:36:36 EST 2022
     */
    long countByExample(UserPermissionViewDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.user_permission_view
     *
     * @mbg.generated Sat Feb 26 19:36:36 EST 2022
     */
    int deleteByExample(UserPermissionViewDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.user_permission_view
     *
     * @mbg.generated Sat Feb 26 19:36:36 EST 2022
     */
    int insert(UserPermissionViewDbo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.user_permission_view
     *
     * @mbg.generated Sat Feb 26 19:36:36 EST 2022
     */
    int insertSelective(UserPermissionViewDbo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.user_permission_view
     *
     * @mbg.generated Sat Feb 26 19:36:36 EST 2022
     */
    List<UserPermissionViewDbo> selectByExample(UserPermissionViewDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.user_permission_view
     *
     * @mbg.generated Sat Feb 26 19:36:36 EST 2022
     */
    int updateByExampleSelective(@Param("record") UserPermissionViewDbo record, @Param("example") UserPermissionViewDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.user_permission_view
     *
     * @mbg.generated Sat Feb 26 19:36:36 EST 2022
     */
    int updateByExample(@Param("record") UserPermissionViewDbo record, @Param("example") UserPermissionViewDboExample example);
}