package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.UserPermissionViewDbo;
import com.zfgc.zfgbb.dbo.UserPermissionViewDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPermissionViewDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_permission_view
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	long countByExample(UserPermissionViewDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_permission_view
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int deleteByExample(UserPermissionViewDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_permission_view
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int insert(UserPermissionViewDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_permission_view
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int insertSelective(UserPermissionViewDbo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_permission_view
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	List<UserPermissionViewDbo> selectByExample(UserPermissionViewDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_permission_view
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int updateByExampleSelective(@Param("record") UserPermissionViewDbo record,
			@Param("example") UserPermissionViewDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_permission_view
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	int updateByExample(@Param("record") UserPermissionViewDbo record,
			@Param("example") UserPermissionViewDboExample example);
}