package com.zfgc.zfgbb.mappers;

import com.zfgc.zfgbb.dbo.UserContactInfoDbo;
import com.zfgc.zfgbb.dbo.UserContactInfoDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserContactInfoDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_contact_info
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	long countByExample(UserContactInfoDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_contact_info
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	int deleteByExample(UserContactInfoDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_contact_info
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	int deleteByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_contact_info
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	int insert(UserContactInfoDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_contact_info
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	int insertSelective(UserContactInfoDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_contact_info
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	List<UserContactInfoDbo> selectByExample(UserContactInfoDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_contact_info
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	UserContactInfoDbo selectByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_contact_info
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	int updateByExampleSelective(@Param("row") UserContactInfoDbo row, @Param("example") UserContactInfoDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_contact_info
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	int updateByExample(@Param("row") UserContactInfoDbo row, @Param("example") UserContactInfoDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_contact_info
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	int updateByPrimaryKeySelective(UserContactInfoDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_contact_info
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	int updateByPrimaryKey(UserContactInfoDbo row);
} 