apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-php-deployment
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-php
  template:
    metadata:
      labels:
        app: apache-php
    spec:
      containers:
        - name: apache
          image: php:7.4-apache
          volumeMounts:
            - mountPath: /usr/local/apache2/conf
              name: apache-config
            - mountPath: /var/www/html
              name: apache-php-content
---
apiVersion: v1
kind: Volume
metadata:
  name: apache-config
spec:
  configMap:
    name: apache-php-config
