apiVersion: v1
kind: Service
metadata:
  name: apache-php-service
  namespace: ${NAMESPACE}
spec:
  selector:
    app: apache-php
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 443
      targetPort: 443
