package com.zfgc.zfgbb.dbo;

import java.time.LocalDateTime;
import java.util.Date;

public class AllMessagesInThreadViewDbo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.all_messages_in_thread_view.thread_id
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    private Integer threadId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.all_messages_in_thread_view.thread_name
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    private String threadName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.all_messages_in_thread_view.locked_flag
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    private Boolean lockedFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.all_messages_in_thread_view.pinned_flag
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    private Boolean pinnedFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.all_messages_in_thread_view.created_ts
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    private Date createdTs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.all_messages_in_thread_view.updated_ts
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    private Date updatedTs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.all_messages_in_thread_view.board_id
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    private Integer boardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.all_messages_in_thread_view.created_user_id
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    private Integer createdUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.all_messages_in_thread_view.view_count
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.all_messages_in_thread_view.message_id
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    private Integer messageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.all_messages_in_thread_view.last_posted_user_id
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    private Integer lastPostedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.all_messages_in_thread_view.last_posted_user
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    private String lastPostedUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.all_messages_in_thread_view.post_ts
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    private LocalDateTime postTs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.all_messages_in_thread_view.post_in_thread
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    private Integer postInThread;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.all_messages_in_thread_view.thread_id
     *
     * @return the value of zfgbb.all_messages_in_thread_view.thread_id
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    public Integer getThreadId() {
        return threadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.all_messages_in_thread_view.thread_id
     *
     * @param threadId the value for zfgbb.all_messages_in_thread_view.thread_id
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    public void setThreadId(Integer threadId) {
        this.threadId = threadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.all_messages_in_thread_view.thread_name
     *
     * @return the value of zfgbb.all_messages_in_thread_view.thread_name
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    public String getThreadName() {
        return threadName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.all_messages_in_thread_view.thread_name
     *
     * @param threadName the value for zfgbb.all_messages_in_thread_view.thread_name
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    public void setThreadName(String threadName) {
        this.threadName = threadName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.all_messages_in_thread_view.locked_flag
     *
     * @return the value of zfgbb.all_messages_in_thread_view.locked_flag
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    public Boolean getLockedFlag() {
        return lockedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.all_messages_in_thread_view.locked_flag
     *
     * @param lockedFlag the value for zfgbb.all_messages_in_thread_view.locked_flag
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    public void setLockedFlag(Boolean lockedFlag) {
        this.lockedFlag = lockedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.all_messages_in_thread_view.pinned_flag
     *
     * @return the value of zfgbb.all_messages_in_thread_view.pinned_flag
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    public Boolean getPinnedFlag() {
        return pinnedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.all_messages_in_thread_view.pinned_flag
     *
     * @param pinnedFlag the value for zfgbb.all_messages_in_thread_view.pinned_flag
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    public void setPinnedFlag(Boolean pinnedFlag) {
        this.pinnedFlag = pinnedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.all_messages_in_thread_view.created_ts
     *
     * @return the value of zfgbb.all_messages_in_thread_view.created_ts
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    public Date getCreatedTs() {
        return createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.all_messages_in_thread_view.created_ts
     *
     * @param createdTs the value for zfgbb.all_messages_in_thread_view.created_ts
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    public void setCreatedTs(Date createdTs) {
        this.createdTs = createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.all_messages_in_thread_view.updated_ts
     *
     * @return the value of zfgbb.all_messages_in_thread_view.updated_ts
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    public Date getUpdatedTs() {
        return updatedTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.all_messages_in_thread_view.updated_ts
     *
     * @param updatedTs the value for zfgbb.all_messages_in_thread_view.updated_ts
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    public void setUpdatedTs(Date updatedTs) {
        this.updatedTs = updatedTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.all_messages_in_thread_view.board_id
     *
     * @return the value of zfgbb.all_messages_in_thread_view.board_id
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    public Integer getBoardId() {
        return boardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.all_messages_in_thread_view.board_id
     *
     * @param boardId the value for zfgbb.all_messages_in_thread_view.board_id
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    public void setBoardId(Integer boardId) {
        this.boardId = boardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.all_messages_in_thread_view.created_user_id
     *
     * @return the value of zfgbb.all_messages_in_thread_view.created_user_id
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    public Integer getCreatedUserId() {
        return createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.all_messages_in_thread_view.created_user_id
     *
     * @param createdUserId the value for zfgbb.all_messages_in_thread_view.created_user_id
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    public void setCreatedUserId(Integer createdUserId) {
        this.createdUserId = createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.all_messages_in_thread_view.view_count
     *
     * @return the value of zfgbb.all_messages_in_thread_view.view_count
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.all_messages_in_thread_view.view_count
     *
     * @param viewCount the value for zfgbb.all_messages_in_thread_view.view_count
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.all_messages_in_thread_view.message_id
     *
     * @return the value of zfgbb.all_messages_in_thread_view.message_id
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    public Integer getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.all_messages_in_thread_view.message_id
     *
     * @param messageId the value for zfgbb.all_messages_in_thread_view.message_id
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.all_messages_in_thread_view.last_posted_user_id
     *
     * @return the value of zfgbb.all_messages_in_thread_view.last_posted_user_id
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    public Integer getLastPostedUserId() {
        return lastPostedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.all_messages_in_thread_view.last_posted_user_id
     *
     * @param lastPostedUserId the value for zfgbb.all_messages_in_thread_view.last_posted_user_id
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    public void setLastPostedUserId(Integer lastPostedUserId) {
        this.lastPostedUserId = lastPostedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.all_messages_in_thread_view.last_posted_user
     *
     * @return the value of zfgbb.all_messages_in_thread_view.last_posted_user
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    public String getLastPostedUser() {
        return lastPostedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.all_messages_in_thread_view.last_posted_user
     *
     * @param lastPostedUser the value for zfgbb.all_messages_in_thread_view.last_posted_user
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    public void setLastPostedUser(String lastPostedUser) {
        this.lastPostedUser = lastPostedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.all_messages_in_thread_view.post_ts
     *
     * @return the value of zfgbb.all_messages_in_thread_view.post_ts
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    public LocalDateTime getPostTs() {
        return postTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.all_messages_in_thread_view.post_ts
     *
     * @param postTs the value for zfgbb.all_messages_in_thread_view.post_ts
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    public void setPostTs(LocalDateTime postTs) {
        this.postTs = postTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.all_messages_in_thread_view.post_in_thread
     *
     * @return the value of zfgbb.all_messages_in_thread_view.post_in_thread
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    public Integer getPostInThread() {
        return postInThread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.all_messages_in_thread_view.post_in_thread
     *
     * @param postInThread the value for zfgbb.all_messages_in_thread_view.post_in_thread
     *
     * @mbg.generated Sun Feb 23 18:52:08 EST 2025
     */
    public void setPostInThread(Integer postInThread) {
        this.postInThread = postInThread;
    }
}