package com.zfgc.zfgbb.dbo;

import java.time.Instant;
import java.time.LocalDate;

import com.zfgc.zfgbb.dbo.AbstractDbo;

public class AttributeDataTypeDbo extends AbstractDbo {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.attribute_data_type.attribute_data_type_id
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	private Integer attributeDataTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.attribute_data_type.type_name
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	private String typeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.attribute_data_type.created_ts
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	private LocalDate createdTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.attribute_data_type.updated_ts
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	private LocalDate updatedTs;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.attribute_data_type.attribute_data_type_id
	 * @return  the value of zfgbb.attribute_data_type.attribute_data_type_id
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	public Integer getAttributeDataTypeId() {
		return attributeDataTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.attribute_data_type.attribute_data_type_id
	 * @param attributeDataTypeId  the value for zfgbb.attribute_data_type.attribute_data_type_id
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	public void setAttributeDataTypeId(Integer attributeDataTypeId) {
		this.attributeDataTypeId = attributeDataTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.attribute_data_type.type_name
	 * @return  the value of zfgbb.attribute_data_type.type_name
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	public String getTypeName() {
		return typeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.attribute_data_type.type_name
	 * @param typeName  the value for zfgbb.attribute_data_type.type_name
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.attribute_data_type.created_ts
	 * @return  the value of zfgbb.attribute_data_type.created_ts
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	public LocalDate getCreatedTs() {
		return createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.attribute_data_type.created_ts
	 * @param createdTs  the value for zfgbb.attribute_data_type.created_ts
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	public void setCreatedTs(LocalDate createdTs) {
		this.createdTs = createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.attribute_data_type.updated_ts
	 * @return  the value of zfgbb.attribute_data_type.updated_ts
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	public LocalDate getUpdatedTs() {
		return updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.attribute_data_type.updated_ts
	 * @param updatedTs  the value for zfgbb.attribute_data_type.updated_ts
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	public void setUpdatedTs(LocalDate updatedTs) {
		this.updatedTs = updatedTs;
	}

	@Override
	public Integer getPkId() {
		return attributeDataTypeId;
	}

	@Override
	public LocalDate getUpdatedTime() {
		return updatedTs;
	}
}