package com.zfgc.zfgbb.dbo;

import java.time.LocalDateTime;

public class AvatarDbo extends AbstractDbo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.avatar.avatar_id
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	private Integer avatarId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.avatar.url
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.avatar.user_id
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.avatar.active_flag
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	private Boolean activeFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.avatar.created_ts
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	private LocalDateTime createdTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.avatar.updated_ts
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	private LocalDateTime updatedTs;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.avatar.avatar_id
	 * @return  the value of zfgbb.avatar.avatar_id
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	public Integer getAvatarId() {
		return avatarId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.avatar.avatar_id
	 * @param avatarId  the value for zfgbb.avatar.avatar_id
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	public void setAvatarId(Integer avatarId) {
		this.avatarId = avatarId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.avatar.url
	 * @return  the value of zfgbb.avatar.url
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.avatar.url
	 * @param url  the value for zfgbb.avatar.url
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.avatar.user_id
	 * @return  the value of zfgbb.avatar.user_id
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.avatar.user_id
	 * @param userId  the value for zfgbb.avatar.user_id
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.avatar.active_flag
	 * @return  the value of zfgbb.avatar.active_flag
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	public Boolean getActiveFlag() {
		return activeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.avatar.active_flag
	 * @param activeFlag  the value for zfgbb.avatar.active_flag
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	public void setActiveFlag(Boolean activeFlag) {
		this.activeFlag = activeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.avatar.created_ts
	 * @return  the value of zfgbb.avatar.created_ts
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	public LocalDateTime getCreatedTs() {
		return createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.avatar.created_ts
	 * @param createdTs  the value for zfgbb.avatar.created_ts
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	public void setCreatedTs(LocalDateTime createdTs) {
		this.createdTs = createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.avatar.updated_ts
	 * @return  the value of zfgbb.avatar.updated_ts
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	public LocalDateTime getUpdatedTs() {
		return updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.avatar.updated_ts
	 * @param updatedTs  the value for zfgbb.avatar.updated_ts
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	public void setUpdatedTs(LocalDateTime updatedTs) {
		this.updatedTs = updatedTs;
	}

	@Override
	public Integer getPkId() {
		return avatarId;
	}

	@Override
	public LocalDateTime getUpdatedTime() {
		return updatedTs;
	}

	@Override
	public LocalDateTime getCreatedTime() {
		return createdTs;
	}
}