package com.zfgc.zfgbb.dbo;


import java.time.LocalDate;

import com.zfgc.zfgbb.dbo.AbstractDbo;
import java.time.LocalDateTime;

public class BBCodeConfigDbo extends AbstractDbo {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.bb_code_config.bb_code_config_id
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	private Integer bbCodeConfigId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.bb_code_config.code
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.bb_code_config.end_tag
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	private String endTag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.bb_code_config.process_content_flag
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	private Boolean processContentFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.bb_code_config.created_ts
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	private LocalDateTime createdTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.bb_code_config.updated_ts
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	private LocalDateTime updatedTs;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.bb_code_config.bb_code_config_id
	 * @return  the value of zfgbb.bb_code_config.bb_code_config_id
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public Integer getBbCodeConfigId() {
		return bbCodeConfigId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.bb_code_config.bb_code_config_id
	 * @param bbCodeConfigId  the value for zfgbb.bb_code_config.bb_code_config_id
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public void setBbCodeConfigId(Integer bbCodeConfigId) {
		this.bbCodeConfigId = bbCodeConfigId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.bb_code_config.code
	 * @return  the value of zfgbb.bb_code_config.code
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.bb_code_config.code
	 * @param code  the value for zfgbb.bb_code_config.code
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.bb_code_config.end_tag
	 * @return  the value of zfgbb.bb_code_config.end_tag
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public String getEndTag() {
		return endTag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.bb_code_config.end_tag
	 * @param endTag  the value for zfgbb.bb_code_config.end_tag
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public void setEndTag(String endTag) {
		this.endTag = endTag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.bb_code_config.process_content_flag
	 * @return  the value of zfgbb.bb_code_config.process_content_flag
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public Boolean getProcessContentFlag() {
		return processContentFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.bb_code_config.process_content_flag
	 * @param processContentFlag  the value for zfgbb.bb_code_config.process_content_flag
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public void setProcessContentFlag(Boolean processContentFlag) {
		this.processContentFlag = processContentFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.bb_code_config.created_ts
	 * @return  the value of zfgbb.bb_code_config.created_ts
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public LocalDateTime getCreatedTs() {
		return createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.bb_code_config.created_ts
	 * @param createdTs  the value for zfgbb.bb_code_config.created_ts
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public void setCreatedTs(LocalDateTime createdTs) {
		this.createdTs = createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.bb_code_config.updated_ts
	 * @return  the value of zfgbb.bb_code_config.updated_ts
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public LocalDateTime getUpdatedTs() {
		return updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.bb_code_config.updated_ts
	 * @param updatedTs  the value for zfgbb.bb_code_config.updated_ts
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public void setUpdatedTs(LocalDateTime updatedTs) {
		this.updatedTs = updatedTs;
	}

	@Override
	public Integer getPkId() {
		return bbCodeConfigId;
	}

	@Override
	public LocalDateTime getUpdatedTime() {
		return updatedTs;
	}
}