package com.zfgc.zfgbb.dbo;

import java.time.Instant;

import com.zfgc.zfgbb.dbo.AbstractDbo;

public class BBCodeAttributeDbo extends AbstractDbo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.bb_code_attribute.bb_code_attribute_id
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    private Integer bbCodeAttributeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.bb_code_attribute.attribute_data_type
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    private Integer attributeDataType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.bb_code_attribute.attribute_index
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    private Integer attributeIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.bb_code_attribute.bb_code_attribute_mode_id
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    private Integer bbCodeAttributeModeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.bb_code_attribute.name
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.bb_code_attribute.created_ts
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    private Instant createdTs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.bb_code_attribute.updated_ts
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    private Instant updatedTs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.bb_code_attribute.bb_code_attribute_id
     *
     * @return the value of zfgbb.bb_code_attribute.bb_code_attribute_id
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    public Integer getBbCodeAttributeId() {
        return bbCodeAttributeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.bb_code_attribute.bb_code_attribute_id
     *
     * @param bbCodeAttributeId the value for zfgbb.bb_code_attribute.bb_code_attribute_id
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    public void setBbCodeAttributeId(Integer bbCodeAttributeId) {
        this.bbCodeAttributeId = bbCodeAttributeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.bb_code_attribute.attribute_data_type
     *
     * @return the value of zfgbb.bb_code_attribute.attribute_data_type
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    public Integer getAttributeDataType() {
        return attributeDataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.bb_code_attribute.attribute_data_type
     *
     * @param attributeDataType the value for zfgbb.bb_code_attribute.attribute_data_type
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    public void setAttributeDataType(Integer attributeDataType) {
        this.attributeDataType = attributeDataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.bb_code_attribute.attribute_index
     *
     * @return the value of zfgbb.bb_code_attribute.attribute_index
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    public Integer getAttributeIndex() {
        return attributeIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.bb_code_attribute.attribute_index
     *
     * @param attributeIndex the value for zfgbb.bb_code_attribute.attribute_index
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    public void setAttributeIndex(Integer attributeIndex) {
        this.attributeIndex = attributeIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.bb_code_attribute.bb_code_attribute_mode_id
     *
     * @return the value of zfgbb.bb_code_attribute.bb_code_attribute_mode_id
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    public Integer getBbCodeAttributeModeId() {
        return bbCodeAttributeModeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.bb_code_attribute.bb_code_attribute_mode_id
     *
     * @param bbCodeAttributeModeId the value for zfgbb.bb_code_attribute.bb_code_attribute_mode_id
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    public void setBbCodeAttributeModeId(Integer bbCodeAttributeModeId) {
        this.bbCodeAttributeModeId = bbCodeAttributeModeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.bb_code_attribute.name
     *
     * @return the value of zfgbb.bb_code_attribute.name
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.bb_code_attribute.name
     *
     * @param name the value for zfgbb.bb_code_attribute.name
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.bb_code_attribute.created_ts
     *
     * @return the value of zfgbb.bb_code_attribute.created_ts
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    public Instant getCreatedTs() {
        return createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.bb_code_attribute.created_ts
     *
     * @param createdTs the value for zfgbb.bb_code_attribute.created_ts
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    public void setCreatedTs(Instant createdTs) {
        this.createdTs = createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.bb_code_attribute.updated_ts
     *
     * @return the value of zfgbb.bb_code_attribute.updated_ts
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    public Instant getUpdatedTs() {
        return updatedTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.bb_code_attribute.updated_ts
     *
     * @param updatedTs the value for zfgbb.bb_code_attribute.updated_ts
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    public void setUpdatedTs(Instant updatedTs) {
        this.updatedTs = updatedTs;
    }

	@Override
	public Integer getRecordId() {
		return bbCodeAttributeId;
	}

	@Override
	public Instant getUpdatedTime() {
		return updatedTs;
	}
}