package com.zfgc.zfgbb.dbo;

import java.time.Instant;

import com.zfgc.zfgbb.dbo.AbstractDbo;

public class BBCodeAttributeModeDbo extends AbstractDbo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.bb_code_attribute_mode.bb_code_attribute_mode_id
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    private Integer bbCodeAttributeModeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.bb_code_attribute_mode.bb_code_config_id
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    private Integer bbCodeConfigId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.bb_code_attribute_mode.content_is_attribute_flag
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    private Boolean contentIsAttributeFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.bb_code_attribute_mode.open_tag
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    private String openTag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.bb_code_attribute_mode.close_tag
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    private String closeTag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.bb_code_attribute_mode.output_content_flag
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    private Boolean outputContentFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.bb_code_attribute_mode.created_ts
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    private Instant createdTs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.bb_code_attribute_mode.updated_ts
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    private Instant updatedTs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.bb_code_attribute_mode.bb_code_attribute_mode_id
     *
     * @return the value of zfgbb.bb_code_attribute_mode.bb_code_attribute_mode_id
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    public Integer getBbCodeAttributeModeId() {
        return bbCodeAttributeModeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.bb_code_attribute_mode.bb_code_attribute_mode_id
     *
     * @param bbCodeAttributeModeId the value for zfgbb.bb_code_attribute_mode.bb_code_attribute_mode_id
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    public void setBbCodeAttributeModeId(Integer bbCodeAttributeModeId) {
        this.bbCodeAttributeModeId = bbCodeAttributeModeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.bb_code_attribute_mode.bb_code_config_id
     *
     * @return the value of zfgbb.bb_code_attribute_mode.bb_code_config_id
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    public Integer getBbCodeConfigId() {
        return bbCodeConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.bb_code_attribute_mode.bb_code_config_id
     *
     * @param bbCodeConfigId the value for zfgbb.bb_code_attribute_mode.bb_code_config_id
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    public void setBbCodeConfigId(Integer bbCodeConfigId) {
        this.bbCodeConfigId = bbCodeConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.bb_code_attribute_mode.content_is_attribute_flag
     *
     * @return the value of zfgbb.bb_code_attribute_mode.content_is_attribute_flag
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    public Boolean getContentIsAttributeFlag() {
        return contentIsAttributeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.bb_code_attribute_mode.content_is_attribute_flag
     *
     * @param contentIsAttributeFlag the value for zfgbb.bb_code_attribute_mode.content_is_attribute_flag
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    public void setContentIsAttributeFlag(Boolean contentIsAttributeFlag) {
        this.contentIsAttributeFlag = contentIsAttributeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.bb_code_attribute_mode.open_tag
     *
     * @return the value of zfgbb.bb_code_attribute_mode.open_tag
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    public String getOpenTag() {
        return openTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.bb_code_attribute_mode.open_tag
     *
     * @param openTag the value for zfgbb.bb_code_attribute_mode.open_tag
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    public void setOpenTag(String openTag) {
        this.openTag = openTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.bb_code_attribute_mode.close_tag
     *
     * @return the value of zfgbb.bb_code_attribute_mode.close_tag
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    public String getCloseTag() {
        return closeTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.bb_code_attribute_mode.close_tag
     *
     * @param closeTag the value for zfgbb.bb_code_attribute_mode.close_tag
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    public void setCloseTag(String closeTag) {
        this.closeTag = closeTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.bb_code_attribute_mode.output_content_flag
     *
     * @return the value of zfgbb.bb_code_attribute_mode.output_content_flag
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    public Boolean getOutputContentFlag() {
        return outputContentFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.bb_code_attribute_mode.output_content_flag
     *
     * @param outputContentFlag the value for zfgbb.bb_code_attribute_mode.output_content_flag
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    public void setOutputContentFlag(Boolean outputContentFlag) {
        this.outputContentFlag = outputContentFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.bb_code_attribute_mode.created_ts
     *
     * @return the value of zfgbb.bb_code_attribute_mode.created_ts
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    public Instant getCreatedTs() {
        return createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.bb_code_attribute_mode.created_ts
     *
     * @param createdTs the value for zfgbb.bb_code_attribute_mode.created_ts
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    public void setCreatedTs(Instant createdTs) {
        this.createdTs = createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.bb_code_attribute_mode.updated_ts
     *
     * @return the value of zfgbb.bb_code_attribute_mode.updated_ts
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    public Instant getUpdatedTs() {
        return updatedTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.bb_code_attribute_mode.updated_ts
     *
     * @param updatedTs the value for zfgbb.bb_code_attribute_mode.updated_ts
     *
     * @mbg.generated Fri Feb 25 00:15:45 EST 2022
     */
    public void setUpdatedTs(Instant updatedTs) {
        this.updatedTs = updatedTs;
    }

	@Override
	public Integer getRecordId() {
		return bbCodeAttributeModeId;
	}

	@Override
	public Instant getUpdatedTime() {
		return updatedTs;
	}
}