package com.zfgc.zfgbb.dbo;

import java.time.Instant;
import java.time.LocalDate;

import com.zfgc.zfgbb.dbo.AbstractDbo;

public class BoardPermissionViewDbo extends AbstractDbo {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.board_permission_view.board_id
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	private Integer boardId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.board_permission_view.permission_id
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	private Integer permissionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.board_permission_view.permission_code
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	private String permissionCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.board_permission_view.permission_name
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	private String permissionName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.board_permission_view.board_id
	 * @return  the value of zfgbb.board_permission_view.board_id
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	public Integer getBoardId() {
		return boardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.board_permission_view.board_id
	 * @param boardId  the value for zfgbb.board_permission_view.board_id
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	public void setBoardId(Integer boardId) {
		this.boardId = boardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.board_permission_view.permission_id
	 * @return  the value of zfgbb.board_permission_view.permission_id
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	public Integer getPermissionId() {
		return permissionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.board_permission_view.permission_id
	 * @param permissionId  the value for zfgbb.board_permission_view.permission_id
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	public void setPermissionId(Integer permissionId) {
		this.permissionId = permissionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.board_permission_view.permission_code
	 * @return  the value of zfgbb.board_permission_view.permission_code
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	public String getPermissionCode() {
		return permissionCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.board_permission_view.permission_code
	 * @param permissionCode  the value for zfgbb.board_permission_view.permission_code
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	public void setPermissionCode(String permissionCode) {
		this.permissionCode = permissionCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.board_permission_view.permission_name
	 * @return  the value of zfgbb.board_permission_view.permission_name
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	public String getPermissionName() {
		return permissionName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.board_permission_view.permission_name
	 * @param permissionName  the value for zfgbb.board_permission_view.permission_name
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	public void setPermissionName(String permissionName) {
		this.permissionName = permissionName;
	}

	@Override
	public Integer getPkId() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public LocalDate getUpdatedTime() {
		// TODO Auto-generated method stub
		return null;
	}
}