package com.zfgc.zfgbb.dbo;

import java.time.LocalDateTime;

public class BoardDbo extends AbstractDbo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.board.board_id
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	private Integer boardId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.board.board_name
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	private String boardName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.board.description
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.board.created_ts
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	private LocalDateTime createdTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.board.updated_ts
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	private LocalDateTime updatedTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.board.category_id
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	private Integer categoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.board.seqno
	 * @mbg.generated  Sun Oct 13 16:34:56 EDT 2024
	 */
	private Integer seqno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.board.parent_board_id
	 * @mbg.generated  Sun Oct 13 16:34:56 EDT 2024
	 */
	private Integer parentBoardId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.board.board_id
	 * @return  the value of zfgbb.board.board_id
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public Integer getBoardId() {
		return boardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.board.board_id
	 * @param boardId  the value for zfgbb.board.board_id
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public void setBoardId(Integer boardId) {
		this.boardId = boardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.board.board_name
	 * @return  the value of zfgbb.board.board_name
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public String getBoardName() {
		return boardName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.board.board_name
	 * @param boardName  the value for zfgbb.board.board_name
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public void setBoardName(String boardName) {
		this.boardName = boardName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.board.description
	 * @return  the value of zfgbb.board.description
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.board.description
	 * @param description  the value for zfgbb.board.description
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.board.created_ts
	 * @return  the value of zfgbb.board.created_ts
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public LocalDateTime getCreatedTs() {
		return createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.board.created_ts
	 * @param createdTs  the value for zfgbb.board.created_ts
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public void setCreatedTs(LocalDateTime createdTs) {
		this.createdTs = createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.board.updated_ts
	 * @return  the value of zfgbb.board.updated_ts
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public LocalDateTime getUpdatedTs() {
		return updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.board.updated_ts
	 * @param updatedTs  the value for zfgbb.board.updated_ts
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public void setUpdatedTs(LocalDateTime updatedTs) {
		this.updatedTs = updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.board.category_id
	 * @return  the value of zfgbb.board.category_id
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public Integer getCategoryId() {
		return categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.board.category_id
	 * @param categoryId  the value for zfgbb.board.category_id
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.board.seqno
	 * @return  the value of zfgbb.board.seqno
	 * @mbg.generated  Sun Oct 13 16:34:56 EDT 2024
	 */
	public Integer getSeqno() {
		return seqno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.board.seqno
	 * @param seqno  the value for zfgbb.board.seqno
	 * @mbg.generated  Sun Oct 13 16:34:56 EDT 2024
	 */
	public void setSeqno(Integer seqno) {
		this.seqno = seqno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.board.parent_board_id
	 * @return  the value of zfgbb.board.parent_board_id
	 * @mbg.generated  Sun Oct 13 16:34:56 EDT 2024
	 */
	public Integer getParentBoardId() {
		return parentBoardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.board.parent_board_id
	 * @param parentBoardId  the value for zfgbb.board.parent_board_id
	 * @mbg.generated  Sun Oct 13 16:34:56 EDT 2024
	 */
	public void setParentBoardId(Integer parentBoardId) {
		this.parentBoardId = parentBoardId;
	}

	@Override
	public Integer getPkId() {
		return boardId;
	}

	@Override
	public LocalDateTime getUpdatedTime() {
		return updatedTs;
	}

	@Override
	public LocalDateTime getCreatedTime() {
		return createdTs;
	}
}