package com.zfgc.zfgbb.dbo;

import java.time.LocalDateTime;

public class BoardSummaryViewDbo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.board_summary.board_id
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	private Integer boardId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.board_summary.description
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.board_summary.board_name
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	private String boardName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.board_summary.thread_count
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	private Long threadCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.board_summary.post_count
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	private Long postCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.board_summary.latest_message_id
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	private Integer latestMessageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.board_summary.latest_thread_id
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	private Integer latestThreadId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.board_summary.latest_message_owner_id
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	private Integer latestMessageOwnerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.board_summary.latest_message_user_name
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	private String latestMessageUserName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.board_summary.latest_message_created_ts
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	private LocalDateTime latestMessageCreatedTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.board_summary.category_id
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	private Integer categoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.board_summary.parent_board_id
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	private Integer parentBoardId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.board_summary.thread_name
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	private String threadName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.board_summary.board_id
	 * @return  the value of zfgbb.board_summary.board_id
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	public Integer getBoardId() {
		return boardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.board_summary.board_id
	 * @param boardId  the value for zfgbb.board_summary.board_id
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	public void setBoardId(Integer boardId) {
		this.boardId = boardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.board_summary.description
	 * @return  the value of zfgbb.board_summary.description
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.board_summary.description
	 * @param description  the value for zfgbb.board_summary.description
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.board_summary.board_name
	 * @return  the value of zfgbb.board_summary.board_name
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	public String getBoardName() {
		return boardName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.board_summary.board_name
	 * @param boardName  the value for zfgbb.board_summary.board_name
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	public void setBoardName(String boardName) {
		this.boardName = boardName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.board_summary.thread_count
	 * @return  the value of zfgbb.board_summary.thread_count
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	public Long getThreadCount() {
		return threadCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.board_summary.thread_count
	 * @param threadCount  the value for zfgbb.board_summary.thread_count
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	public void setThreadCount(Long threadCount) {
		this.threadCount = threadCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.board_summary.post_count
	 * @return  the value of zfgbb.board_summary.post_count
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	public Long getPostCount() {
		return postCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.board_summary.post_count
	 * @param postCount  the value for zfgbb.board_summary.post_count
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	public void setPostCount(Long postCount) {
		this.postCount = postCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.board_summary.latest_message_id
	 * @return  the value of zfgbb.board_summary.latest_message_id
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	public Integer getLatestMessageId() {
		return latestMessageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.board_summary.latest_message_id
	 * @param latestMessageId  the value for zfgbb.board_summary.latest_message_id
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	public void setLatestMessageId(Integer latestMessageId) {
		this.latestMessageId = latestMessageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.board_summary.latest_thread_id
	 * @return  the value of zfgbb.board_summary.latest_thread_id
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	public Integer getLatestThreadId() {
		return latestThreadId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.board_summary.latest_thread_id
	 * @param latestThreadId  the value for zfgbb.board_summary.latest_thread_id
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	public void setLatestThreadId(Integer latestThreadId) {
		this.latestThreadId = latestThreadId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.board_summary.latest_message_owner_id
	 * @return  the value of zfgbb.board_summary.latest_message_owner_id
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	public Integer getLatestMessageOwnerId() {
		return latestMessageOwnerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.board_summary.latest_message_owner_id
	 * @param latestMessageOwnerId  the value for zfgbb.board_summary.latest_message_owner_id
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	public void setLatestMessageOwnerId(Integer latestMessageOwnerId) {
		this.latestMessageOwnerId = latestMessageOwnerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.board_summary.latest_message_user_name
	 * @return  the value of zfgbb.board_summary.latest_message_user_name
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	public String getLatestMessageUserName() {
		return latestMessageUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.board_summary.latest_message_user_name
	 * @param latestMessageUserName  the value for zfgbb.board_summary.latest_message_user_name
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	public void setLatestMessageUserName(String latestMessageUserName) {
		this.latestMessageUserName = latestMessageUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.board_summary.latest_message_created_ts
	 * @return  the value of zfgbb.board_summary.latest_message_created_ts
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	public LocalDateTime getLatestMessageCreatedTs() {
		return latestMessageCreatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.board_summary.latest_message_created_ts
	 * @param latestMessageCreatedTs  the value for zfgbb.board_summary.latest_message_created_ts
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	public void setLatestMessageCreatedTs(LocalDateTime latestMessageCreatedTs) {
		this.latestMessageCreatedTs = latestMessageCreatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.board_summary.category_id
	 * @return  the value of zfgbb.board_summary.category_id
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	public Integer getCategoryId() {
		return categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.board_summary.category_id
	 * @param categoryId  the value for zfgbb.board_summary.category_id
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.board_summary.parent_board_id
	 * @return  the value of zfgbb.board_summary.parent_board_id
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	public Integer getParentBoardId() {
		return parentBoardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.board_summary.parent_board_id
	 * @param parentBoardId  the value for zfgbb.board_summary.parent_board_id
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	public void setParentBoardId(Integer parentBoardId) {
		this.parentBoardId = parentBoardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.board_summary.thread_name
	 * @return  the value of zfgbb.board_summary.thread_name
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	public String getThreadName() {
		return threadName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.board_summary.thread_name
	 * @param threadName  the value for zfgbb.board_summary.thread_name
	 * @mbg.generated  Sun Feb 23 10:46:24 EST 2025
	 */
	public void setThreadName(String threadName) {
		this.threadName = threadName;
	}
}