package com.zfgc.zfgbb.dbo;

import java.time.Instant;
import java.util.Date;

import com.zfgc.zfgbb.dbo.AbstractDbo;

public class BoardDbo extends AbstractDbo{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.board.board_id
	 * @mbg.generated  Wed Feb 23 22:16:25 EST 2022
	 */
	private Integer boardId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.board.board_name
	 * @mbg.generated  Wed Feb 23 22:16:25 EST 2022
	 */
	private String boardName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.board.description
	 * @mbg.generated  Wed Feb 23 22:16:25 EST 2022
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.board.created_ts
	 * @mbg.generated  Wed Feb 23 22:16:25 EST 2022
	 */
	private Instant createdTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.board.updated_ts
	 * @mbg.generated  Wed Feb 23 22:16:25 EST 2022
	 */
	private Instant updatedTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.board.category_id
	 * @mbg.generated  Wed Feb 23 22:16:25 EST 2022
	 */
	private Integer categoryId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.board.board_id
	 * @return  the value of zfgbb.board.board_id
	 * @mbg.generated  Wed Feb 23 22:16:25 EST 2022
	 */
	public Integer getBoardId() {
		return boardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.board.board_id
	 * @param boardId  the value for zfgbb.board.board_id
	 * @mbg.generated  Wed Feb 23 22:16:25 EST 2022
	 */
	public void setBoardId(Integer boardId) {
		this.boardId = boardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.board.board_name
	 * @return  the value of zfgbb.board.board_name
	 * @mbg.generated  Wed Feb 23 22:16:25 EST 2022
	 */
	public String getBoardName() {
		return boardName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.board.board_name
	 * @param boardName  the value for zfgbb.board.board_name
	 * @mbg.generated  Wed Feb 23 22:16:25 EST 2022
	 */
	public void setBoardName(String boardName) {
		this.boardName = boardName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.board.description
	 * @return  the value of zfgbb.board.description
	 * @mbg.generated  Wed Feb 23 22:16:25 EST 2022
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.board.description
	 * @param description  the value for zfgbb.board.description
	 * @mbg.generated  Wed Feb 23 22:16:25 EST 2022
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.board.created_ts
	 * @return  the value of zfgbb.board.created_ts
	 * @mbg.generated  Wed Feb 23 22:16:25 EST 2022
	 */
	public Instant getCreatedTs() {
		return createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.board.created_ts
	 * @param createdTs  the value for zfgbb.board.created_ts
	 * @mbg.generated  Wed Feb 23 22:16:25 EST 2022
	 */
	public void setCreatedTs(Instant createdTs) {
		this.createdTs = createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.board.updated_ts
	 * @return  the value of zfgbb.board.updated_ts
	 * @mbg.generated  Wed Feb 23 22:16:25 EST 2022
	 */
	public Instant getUpdatedTs() {
		return updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.board.updated_ts
	 * @param updatedTs  the value for zfgbb.board.updated_ts
	 * @mbg.generated  Wed Feb 23 22:16:25 EST 2022
	 */
	public void setUpdatedTs(Instant updatedTs) {
		this.updatedTs = updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.board.category_id
	 * @return  the value of zfgbb.board.category_id
	 * @mbg.generated  Wed Feb 23 22:16:25 EST 2022
	 */
	public Integer getCategoryId() {
		return categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.board.category_id
	 * @param categoryId  the value for zfgbb.board.category_id
	 * @mbg.generated  Wed Feb 23 22:16:25 EST 2022
	 */
	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Override
	public Integer getRecordId() {
		return boardId;
	}

	@Override
	public Instant getUpdatedTime() {
		return updatedTs;
	}
}