package com.zfgc.zfgbb.dbo;

import java.time.LocalDate;

import com.zfgc.zfgbb.dbo.AbstractDbo;
import java.time.LocalDateTime;

public class CategoryDbo extends AbstractDbo{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.category.category_id
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	private Integer categoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.category.category_name
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	private String categoryName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.category.description
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.category.created_ts
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	private LocalDateTime createdTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.category.updated_ts
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	private LocalDateTime updatedTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.category.parent_board_id
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	private Integer parentBoardId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.category.category_id
	 * @return  the value of zfgbb.category.category_id
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public Integer getCategoryId() {
		return categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.category.category_id
	 * @param categoryId  the value for zfgbb.category.category_id
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.category.category_name
	 * @return  the value of zfgbb.category.category_name
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public String getCategoryName() {
		return categoryName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.category.category_name
	 * @param categoryName  the value for zfgbb.category.category_name
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.category.description
	 * @return  the value of zfgbb.category.description
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.category.description
	 * @param description  the value for zfgbb.category.description
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.category.created_ts
	 * @return  the value of zfgbb.category.created_ts
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public LocalDateTime getCreatedTs() {
		return createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.category.created_ts
	 * @param createdTs  the value for zfgbb.category.created_ts
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public void setCreatedTs(LocalDateTime createdTs) {
		this.createdTs = createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.category.updated_ts
	 * @return  the value of zfgbb.category.updated_ts
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public LocalDateTime getUpdatedTs() {
		return updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.category.updated_ts
	 * @param updatedTs  the value for zfgbb.category.updated_ts
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public void setUpdatedTs(LocalDateTime updatedTs) {
		this.updatedTs = updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.category.parent_board_id
	 * @return  the value of zfgbb.category.parent_board_id
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public Integer getParentBoardId() {
		return parentBoardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.category.parent_board_id
	 * @param parentBoardId  the value for zfgbb.category.parent_board_id
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public void setParentBoardId(Integer parentBoardId) {
		this.parentBoardId = parentBoardId;
	}

	@Override
	public Integer getPkId() {
		return categoryId;
	}

	@Override
	public LocalDateTime getUpdatedTime() {
		// TODO Auto-generated method stub
		return updatedTs;
	}
}