package com.zfgc.zfgbb.dbo;

public class ChildBoardViewDbo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.child_board_view.board_id
	 * @mbg.generated  Mon Oct 14 23:44:38 EDT 2024
	 */
	private Integer boardId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.child_board_view.board_name
	 * @mbg.generated  Mon Oct 14 23:44:38 EDT 2024
	 */
	private String boardName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.child_board_view.parent_board_id
	 * @mbg.generated  Mon Oct 14 23:44:38 EDT 2024
	 */
	private Integer parentBoardId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.child_board_view.board_id
	 * @return  the value of zfgbb.child_board_view.board_id
	 * @mbg.generated  Mon Oct 14 23:44:38 EDT 2024
	 */
	public Integer getBoardId() {
		return boardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.child_board_view.board_id
	 * @param boardId  the value for zfgbb.child_board_view.board_id
	 * @mbg.generated  Mon Oct 14 23:44:38 EDT 2024
	 */
	public void setBoardId(Integer boardId) {
		this.boardId = boardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.child_board_view.board_name
	 * @return  the value of zfgbb.child_board_view.board_name
	 * @mbg.generated  Mon Oct 14 23:44:38 EDT 2024
	 */
	public String getBoardName() {
		return boardName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.child_board_view.board_name
	 * @param boardName  the value for zfgbb.child_board_view.board_name
	 * @mbg.generated  Mon Oct 14 23:44:38 EDT 2024
	 */
	public void setBoardName(String boardName) {
		this.boardName = boardName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.child_board_view.parent_board_id
	 * @return  the value of zfgbb.child_board_view.parent_board_id
	 * @mbg.generated  Mon Oct 14 23:44:38 EDT 2024
	 */
	public Integer getParentBoardId() {
		return parentBoardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.child_board_view.parent_board_id
	 * @param parentBoardId  the value for zfgbb.child_board_view.parent_board_id
	 * @mbg.generated  Mon Oct 14 23:44:38 EDT 2024
	 */
	public void setParentBoardId(Integer parentBoardId) {
		this.parentBoardId = parentBoardId;
	}
}