package com.zfgc.zfgbb.dbo;

import java.time.LocalDateTime;

public class ContentResourceDbo extends AbstractDbo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.content_resource.content_resource_id
	 * @mbg.generated  Sun Jan 12 17:44:32 EST 2025
	 */
	private Integer contentResourceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.content_resource.content_type_id
	 * @mbg.generated  Sun Jan 12 17:44:32 EST 2025
	 */
	private Integer contentTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.content_resource.uploaded_user_id
	 * @mbg.generated  Sun Jan 12 17:44:32 EST 2025
	 */
	private Integer uploadedUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.content_resource.filename
	 * @mbg.generated  Sun Jan 12 17:44:32 EST 2025
	 */
	private String filename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.content_resource.checksum
	 * @mbg.generated  Sun Jan 12 17:44:32 EST 2025
	 */
	private String checksum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.content_resource.file_ext
	 * @mbg.generated  Sun Jan 12 17:44:32 EST 2025
	 */
	private String fileExt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.content_resource.mime_type
	 * @mbg.generated  Sun Jan 12 17:44:32 EST 2025
	 */
	private String mimeType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.content_resource.created_ts
	 * @mbg.generated  Sun Jan 12 17:44:32 EST 2025
	 */
	private LocalDateTime createdTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.content_resource.updated_ts
	 * @mbg.generated  Sun Jan 12 17:44:32 EST 2025
	 */
	private LocalDateTime updatedTs;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.content_resource.content_resource_id
	 * @return  the value of zfgbb.content_resource.content_resource_id
	 * @mbg.generated  Sun Jan 12 17:44:32 EST 2025
	 */
	public Integer getContentResourceId() {
		return contentResourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.content_resource.content_resource_id
	 * @param contentResourceId  the value for zfgbb.content_resource.content_resource_id
	 * @mbg.generated  Sun Jan 12 17:44:32 EST 2025
	 */
	public void setContentResourceId(Integer contentResourceId) {
		this.contentResourceId = contentResourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.content_resource.content_type_id
	 * @return  the value of zfgbb.content_resource.content_type_id
	 * @mbg.generated  Sun Jan 12 17:44:32 EST 2025
	 */
	public Integer getContentTypeId() {
		return contentTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.content_resource.content_type_id
	 * @param contentTypeId  the value for zfgbb.content_resource.content_type_id
	 * @mbg.generated  Sun Jan 12 17:44:32 EST 2025
	 */
	public void setContentTypeId(Integer contentTypeId) {
		this.contentTypeId = contentTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.content_resource.uploaded_user_id
	 * @return  the value of zfgbb.content_resource.uploaded_user_id
	 * @mbg.generated  Sun Jan 12 17:44:32 EST 2025
	 */
	public Integer getUploadedUserId() {
		return uploadedUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.content_resource.uploaded_user_id
	 * @param uploadedUserId  the value for zfgbb.content_resource.uploaded_user_id
	 * @mbg.generated  Sun Jan 12 17:44:32 EST 2025
	 */
	public void setUploadedUserId(Integer uploadedUserId) {
		this.uploadedUserId = uploadedUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.content_resource.filename
	 * @return  the value of zfgbb.content_resource.filename
	 * @mbg.generated  Sun Jan 12 17:44:32 EST 2025
	 */
	public String getFilename() {
		return filename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.content_resource.filename
	 * @param filename  the value for zfgbb.content_resource.filename
	 * @mbg.generated  Sun Jan 12 17:44:32 EST 2025
	 */
	public void setFilename(String filename) {
		this.filename = filename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.content_resource.checksum
	 * @return  the value of zfgbb.content_resource.checksum
	 * @mbg.generated  Sun Jan 12 17:44:32 EST 2025
	 */
	public String getChecksum() {
		return checksum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.content_resource.checksum
	 * @param checksum  the value for zfgbb.content_resource.checksum
	 * @mbg.generated  Sun Jan 12 17:44:32 EST 2025
	 */
	public void setChecksum(String checksum) {
		this.checksum = checksum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.content_resource.file_ext
	 * @return  the value of zfgbb.content_resource.file_ext
	 * @mbg.generated  Sun Jan 12 17:44:32 EST 2025
	 */
	public String getFileExt() {
		return fileExt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.content_resource.file_ext
	 * @param fileExt  the value for zfgbb.content_resource.file_ext
	 * @mbg.generated  Sun Jan 12 17:44:32 EST 2025
	 */
	public void setFileExt(String fileExt) {
		this.fileExt = fileExt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.content_resource.mime_type
	 * @return  the value of zfgbb.content_resource.mime_type
	 * @mbg.generated  Sun Jan 12 17:44:32 EST 2025
	 */
	public String getMimeType() {
		return mimeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.content_resource.mime_type
	 * @param mimeType  the value for zfgbb.content_resource.mime_type
	 * @mbg.generated  Sun Jan 12 17:44:32 EST 2025
	 */
	public void setMimeType(String mimeType) {
		this.mimeType = mimeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.content_resource.created_ts
	 * @return  the value of zfgbb.content_resource.created_ts
	 * @mbg.generated  Sun Jan 12 17:44:32 EST 2025
	 */
	public LocalDateTime getCreatedTs() {
		return createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.content_resource.created_ts
	 * @param createdTs  the value for zfgbb.content_resource.created_ts
	 * @mbg.generated  Sun Jan 12 17:44:32 EST 2025
	 */
	public void setCreatedTs(LocalDateTime createdTs) {
		this.createdTs = createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.content_resource.updated_ts
	 * @return  the value of zfgbb.content_resource.updated_ts
	 * @mbg.generated  Sun Jan 12 17:44:32 EST 2025
	 */
	public LocalDateTime getUpdatedTs() {
		return updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.content_resource.updated_ts
	 * @param updatedTs  the value for zfgbb.content_resource.updated_ts
	 * @mbg.generated  Sun Jan 12 17:44:32 EST 2025
	 */
	public void setUpdatedTs(LocalDateTime updatedTs) {
		this.updatedTs = updatedTs;
	}

	/**
	 * MyBatis generated via zfgbb-mybatis
	 * @mbg.generated  2025-01-12T17:44:32.055214700
	 */
	@Override
	public Integer getPkId() {
		return this.contentResourceId;
	}

	/**
	 * MyBatis generated via zfgbb-mybatis
	 * @mbg.generated  2025-01-12T17:44:32.055214700
	 */
	@Override
	public LocalDateTime getUpdatedTime() {
		return this.updatedTs;
	}

	/**
	 * MyBatis generated via zfgbb-mybatis
	 * @mbg.generated  2025-01-12T17:44:32.055214700
	 */
	@Override
	public LocalDateTime getCreatedTime() {
		return this.createdTs;
	}

}