package com.zfgc.zfgbb.dbo;

import java.time.LocalDate;
import java.time.LocalDateTime;

public class CurrentMessageDbo extends AbstractDbo {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.current_message_view.message_id
	 * @mbg.generated  Sat Aug 03 19:49:43 EDT 2024
	 */
	private Integer messageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.current_message_view.owner_id
	 * @mbg.generated  Sat Aug 03 19:49:43 EDT 2024
	 */
	private Integer ownerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.current_message_view.thread_id
	 * @mbg.generated  Sat Aug 03 19:49:43 EDT 2024
	 */
	private Integer threadId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.current_message_view.message_text
	 * @mbg.generated  Sat Aug 03 19:49:43 EDT 2024
	 */
	private String messageText;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.current_message_view.message_history_id
	 * @mbg.generated  Sat Aug 03 19:49:43 EDT 2024
	 */
	private Integer messageHistoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.current_message_view.post_in_thread
	 * @mbg.generated  Sat Aug 03 19:49:43 EDT 2024
	 */
	private Integer postInThread;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.current_message_view.message_id
	 * @return  the value of zfgbb.current_message_view.message_id
	 * @mbg.generated  Sat Aug 03 19:49:43 EDT 2024
	 */
	public Integer getMessageId() {
		return messageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.current_message_view.message_id
	 * @param messageId  the value for zfgbb.current_message_view.message_id
	 * @mbg.generated  Sat Aug 03 19:49:43 EDT 2024
	 */
	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.current_message_view.owner_id
	 * @return  the value of zfgbb.current_message_view.owner_id
	 * @mbg.generated  Sat Aug 03 19:49:43 EDT 2024
	 */
	public Integer getOwnerId() {
		return ownerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.current_message_view.owner_id
	 * @param ownerId  the value for zfgbb.current_message_view.owner_id
	 * @mbg.generated  Sat Aug 03 19:49:43 EDT 2024
	 */
	public void setOwnerId(Integer ownerId) {
		this.ownerId = ownerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.current_message_view.thread_id
	 * @return  the value of zfgbb.current_message_view.thread_id
	 * @mbg.generated  Sat Aug 03 19:49:43 EDT 2024
	 */
	public Integer getThreadId() {
		return threadId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.current_message_view.thread_id
	 * @param threadId  the value for zfgbb.current_message_view.thread_id
	 * @mbg.generated  Sat Aug 03 19:49:43 EDT 2024
	 */
	public void setThreadId(Integer threadId) {
		this.threadId = threadId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.current_message_view.message_text
	 * @return  the value of zfgbb.current_message_view.message_text
	 * @mbg.generated  Sat Aug 03 19:49:43 EDT 2024
	 */
	public String getMessageText() {
		return messageText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.current_message_view.message_text
	 * @param messageText  the value for zfgbb.current_message_view.message_text
	 * @mbg.generated  Sat Aug 03 19:49:43 EDT 2024
	 */
	public void setMessageText(String messageText) {
		this.messageText = messageText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.current_message_view.message_history_id
	 * @return  the value of zfgbb.current_message_view.message_history_id
	 * @mbg.generated  Sat Aug 03 19:49:43 EDT 2024
	 */
	public Integer getMessageHistoryId() {
		return messageHistoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.current_message_view.message_history_id
	 * @param messageHistoryId  the value for zfgbb.current_message_view.message_history_id
	 * @mbg.generated  Sat Aug 03 19:49:43 EDT 2024
	 */
	public void setMessageHistoryId(Integer messageHistoryId) {
		this.messageHistoryId = messageHistoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.current_message_view.post_in_thread
	 * @return  the value of zfgbb.current_message_view.post_in_thread
	 * @mbg.generated  Sat Aug 03 19:49:43 EDT 2024
	 */
	public Integer getPostInThread() {
		return postInThread;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.current_message_view.post_in_thread
	 * @param postInThread  the value for zfgbb.current_message_view.post_in_thread
	 * @mbg.generated  Sat Aug 03 19:49:43 EDT 2024
	 */
	public void setPostInThread(Integer postInThread) {
		this.postInThread = postInThread;
	}

	@Override
	public Integer getPkId() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public LocalDateTime getUpdatedTime() {
		// TODO Auto-generated method stub
		return null;
	}
}