package com.zfgc.zfgbb.dbo;

import java.time.LocalDateTime;

public class FileAttachmentDbo extends AbstractDbo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.file_attachments.file_attachment_id
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	private Integer fileAttachmentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.file_attachments.message_id
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	private Integer messageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.file_attachments.filename
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	private String filename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.file_attachments.checksum
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	private String checksum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.file_attachments.file_ext
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	private String fileExt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.file_attachments.mime_type
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	private String mimeType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.file_attachments.active_flag
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	private Boolean activeFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.file_attachments.created_ts
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	private LocalDateTime createdTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.file_attachments.updated_ts
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	private LocalDateTime updatedTs;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.file_attachments.file_attachment_id
	 * @return  the value of zfgbb.file_attachments.file_attachment_id
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	public Integer getFileAttachmentId() {
		return fileAttachmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.file_attachments.file_attachment_id
	 * @param fileAttachmentId  the value for zfgbb.file_attachments.file_attachment_id
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	public void setFileAttachmentId(Integer fileAttachmentId) {
		this.fileAttachmentId = fileAttachmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.file_attachments.message_id
	 * @return  the value of zfgbb.file_attachments.message_id
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	public Integer getMessageId() {
		return messageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.file_attachments.message_id
	 * @param messageId  the value for zfgbb.file_attachments.message_id
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.file_attachments.filename
	 * @return  the value of zfgbb.file_attachments.filename
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	public String getFilename() {
		return filename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.file_attachments.filename
	 * @param filename  the value for zfgbb.file_attachments.filename
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	public void setFilename(String filename) {
		this.filename = filename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.file_attachments.checksum
	 * @return  the value of zfgbb.file_attachments.checksum
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	public String getChecksum() {
		return checksum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.file_attachments.checksum
	 * @param checksum  the value for zfgbb.file_attachments.checksum
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	public void setChecksum(String checksum) {
		this.checksum = checksum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.file_attachments.file_ext
	 * @return  the value of zfgbb.file_attachments.file_ext
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	public String getFileExt() {
		return fileExt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.file_attachments.file_ext
	 * @param fileExt  the value for zfgbb.file_attachments.file_ext
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	public void setFileExt(String fileExt) {
		this.fileExt = fileExt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.file_attachments.mime_type
	 * @return  the value of zfgbb.file_attachments.mime_type
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	public String getMimeType() {
		return mimeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.file_attachments.mime_type
	 * @param mimeType  the value for zfgbb.file_attachments.mime_type
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	public void setMimeType(String mimeType) {
		this.mimeType = mimeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.file_attachments.active_flag
	 * @return  the value of zfgbb.file_attachments.active_flag
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	public Boolean getActiveFlag() {
		return activeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.file_attachments.active_flag
	 * @param activeFlag  the value for zfgbb.file_attachments.active_flag
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	public void setActiveFlag(Boolean activeFlag) {
		this.activeFlag = activeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.file_attachments.created_ts
	 * @return  the value of zfgbb.file_attachments.created_ts
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	public LocalDateTime getCreatedTs() {
		return createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.file_attachments.created_ts
	 * @param createdTs  the value for zfgbb.file_attachments.created_ts
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	public void setCreatedTs(LocalDateTime createdTs) {
		this.createdTs = createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.file_attachments.updated_ts
	 * @return  the value of zfgbb.file_attachments.updated_ts
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	public LocalDateTime getUpdatedTs() {
		return updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.file_attachments.updated_ts
	 * @param updatedTs  the value for zfgbb.file_attachments.updated_ts
	 * @mbg.generated  Sun Sep 29 14:51:19 EDT 2024
	 */
	public void setUpdatedTs(LocalDateTime updatedTs) {
		this.updatedTs = updatedTs;
	}

	@Override
	public Integer getPkId() {
		return fileAttachmentId;
	}

	@Override
	public LocalDateTime getUpdatedTime() {
		return updatedTs;
	}

	@Override
	public LocalDateTime getCreatedTime() {
		return createdTs;
	}
}