package com.zfgc.zfgbb.dbo;

import java.time.LocalDateTime;

public class FileAttachmentDbo extends AbstractDbo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.file_attachments.file_attachment_id
	 * @mbg.generated  Mon Oct 07 21:34:11 EDT 2024
	 */
	private Integer fileAttachmentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.file_attachments.message_id
	 * @mbg.generated  Mon Oct 07 21:34:11 EDT 2024
	 */
	private Integer messageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.file_attachments.active_flag
	 * @mbg.generated  Mon Oct 07 21:34:11 EDT 2024
	 */
	private Boolean activeFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.file_attachments.created_ts
	 * @mbg.generated  Mon Oct 07 21:34:11 EDT 2024
	 */
	private LocalDateTime createdTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.file_attachments.updated_ts
	 * @mbg.generated  Mon Oct 07 21:34:11 EDT 2024
	 */
	private LocalDateTime updatedTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.file_attachments.content_resource_id
	 * @mbg.generated  Mon Oct 07 21:34:11 EDT 2024
	 */
	private Integer contentResourceId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.file_attachments.file_attachment_id
	 * @return  the value of zfgbb.file_attachments.file_attachment_id
	 * @mbg.generated  Mon Oct 07 21:34:11 EDT 2024
	 */
	public Integer getFileAttachmentId() {
		return fileAttachmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.file_attachments.file_attachment_id
	 * @param fileAttachmentId  the value for zfgbb.file_attachments.file_attachment_id
	 * @mbg.generated  Mon Oct 07 21:34:11 EDT 2024
	 */
	public void setFileAttachmentId(Integer fileAttachmentId) {
		this.fileAttachmentId = fileAttachmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.file_attachments.message_id
	 * @return  the value of zfgbb.file_attachments.message_id
	 * @mbg.generated  Mon Oct 07 21:34:11 EDT 2024
	 */
	public Integer getMessageId() {
		return messageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.file_attachments.message_id
	 * @param messageId  the value for zfgbb.file_attachments.message_id
	 * @mbg.generated  Mon Oct 07 21:34:11 EDT 2024
	 */
	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.file_attachments.active_flag
	 * @return  the value of zfgbb.file_attachments.active_flag
	 * @mbg.generated  Mon Oct 07 21:34:11 EDT 2024
	 */
	public Boolean getActiveFlag() {
		return activeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.file_attachments.active_flag
	 * @param activeFlag  the value for zfgbb.file_attachments.active_flag
	 * @mbg.generated  Mon Oct 07 21:34:11 EDT 2024
	 */
	public void setActiveFlag(Boolean activeFlag) {
		this.activeFlag = activeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.file_attachments.created_ts
	 * @return  the value of zfgbb.file_attachments.created_ts
	 * @mbg.generated  Mon Oct 07 21:34:11 EDT 2024
	 */
	public LocalDateTime getCreatedTs() {
		return createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.file_attachments.created_ts
	 * @param createdTs  the value for zfgbb.file_attachments.created_ts
	 * @mbg.generated  Mon Oct 07 21:34:11 EDT 2024
	 */
	public void setCreatedTs(LocalDateTime createdTs) {
		this.createdTs = createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.file_attachments.updated_ts
	 * @return  the value of zfgbb.file_attachments.updated_ts
	 * @mbg.generated  Mon Oct 07 21:34:11 EDT 2024
	 */
	public LocalDateTime getUpdatedTs() {
		return updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.file_attachments.updated_ts
	 * @param updatedTs  the value for zfgbb.file_attachments.updated_ts
	 * @mbg.generated  Mon Oct 07 21:34:11 EDT 2024
	 */
	public void setUpdatedTs(LocalDateTime updatedTs) {
		this.updatedTs = updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.file_attachments.content_resource_id
	 * @return  the value of zfgbb.file_attachments.content_resource_id
	 * @mbg.generated  Mon Oct 07 21:34:11 EDT 2024
	 */
	public Integer getContentResourceId() {
		return contentResourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.file_attachments.content_resource_id
	 * @param contentResourceId  the value for zfgbb.file_attachments.content_resource_id
	 * @mbg.generated  Mon Oct 07 21:34:11 EDT 2024
	 */
	public void setContentResourceId(Integer contentResourceId) {
		this.contentResourceId = contentResourceId;
	}

	@Override
	public Integer getPkId() {
		return fileAttachmentId;
	}

	@Override
	public LocalDateTime getUpdatedTime() {
		return updatedTs;
	}

	@Override
	public LocalDateTime getCreatedTime() {
		return createdTs;
	}
}