package com.zfgc.zfgbb.dbo;

import java.time.LocalDateTime;

public class IpAddressDbo extends AbstractDbo {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.ip_address.ip_address_id
	 * @mbg.generated  Mon Jul 08 22:45:25 EDT 2024
	 */
	private Integer ipAddressId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.ip_address.ip
	 * @mbg.generated  Mon Jul 08 22:45:25 EDT 2024
	 */
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.ip_address.ip_v6_flag
	 * @mbg.generated  Mon Jul 08 22:45:25 EDT 2024
	 */
	private Boolean ipV6Flag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.ip_address.is_spammer_flag
	 * @mbg.generated  Mon Jul 08 22:45:25 EDT 2024
	 */
	private Boolean isSpammerFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.ip_address.created_ts
	 * @mbg.generated  Mon Jul 08 22:45:25 EDT 2024
	 */
	private LocalDateTime createdTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.ip_address.updated_ts
	 * @mbg.generated  Mon Jul 08 22:45:25 EDT 2024
	 */
	private LocalDateTime updatedTs;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.ip_address.ip_address_id
	 * @return  the value of zfgbb.ip_address.ip_address_id
	 * @mbg.generated  Mon Jul 08 22:45:25 EDT 2024
	 */
	public Integer getIpAddressId() {
		return ipAddressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.ip_address.ip_address_id
	 * @param ipAddressId  the value for zfgbb.ip_address.ip_address_id
	 * @mbg.generated  Mon Jul 08 22:45:25 EDT 2024
	 */
	public void setIpAddressId(Integer ipAddressId) {
		this.ipAddressId = ipAddressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.ip_address.ip
	 * @return  the value of zfgbb.ip_address.ip
	 * @mbg.generated  Mon Jul 08 22:45:25 EDT 2024
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.ip_address.ip
	 * @param ip  the value for zfgbb.ip_address.ip
	 * @mbg.generated  Mon Jul 08 22:45:25 EDT 2024
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.ip_address.ip_v6_flag
	 * @return  the value of zfgbb.ip_address.ip_v6_flag
	 * @mbg.generated  Mon Jul 08 22:45:25 EDT 2024
	 */
	public Boolean getIpV6Flag() {
		return ipV6Flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.ip_address.ip_v6_flag
	 * @param ipV6Flag  the value for zfgbb.ip_address.ip_v6_flag
	 * @mbg.generated  Mon Jul 08 22:45:25 EDT 2024
	 */
	public void setIpV6Flag(Boolean ipV6Flag) {
		this.ipV6Flag = ipV6Flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.ip_address.is_spammer_flag
	 * @return  the value of zfgbb.ip_address.is_spammer_flag
	 * @mbg.generated  Mon Jul 08 22:45:25 EDT 2024
	 */
	public Boolean getIsSpammerFlag() {
		return isSpammerFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.ip_address.is_spammer_flag
	 * @param isSpammerFlag  the value for zfgbb.ip_address.is_spammer_flag
	 * @mbg.generated  Mon Jul 08 22:45:25 EDT 2024
	 */
	public void setIsSpammerFlag(Boolean isSpammerFlag) {
		this.isSpammerFlag = isSpammerFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.ip_address.created_ts
	 * @return  the value of zfgbb.ip_address.created_ts
	 * @mbg.generated  Mon Jul 08 22:45:25 EDT 2024
	 */
	public LocalDateTime getCreatedTs() {
		return createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.ip_address.created_ts
	 * @param createdTs  the value for zfgbb.ip_address.created_ts
	 * @mbg.generated  Mon Jul 08 22:45:25 EDT 2024
	 */
	public void setCreatedTs(LocalDateTime createdTs) {
		this.createdTs = createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.ip_address.updated_ts
	 * @return  the value of zfgbb.ip_address.updated_ts
	 * @mbg.generated  Mon Jul 08 22:45:25 EDT 2024
	 */
	public LocalDateTime getUpdatedTs() {
		return updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.ip_address.updated_ts
	 * @param updatedTs  the value for zfgbb.ip_address.updated_ts
	 * @mbg.generated  Mon Jul 08 22:45:25 EDT 2024
	 */
	public void setUpdatedTs(LocalDateTime updatedTs) {
		this.updatedTs = updatedTs;
	}

	@Override
	public Integer getPkId() {
		return ipAddressId;
	}

	@Override
	public LocalDateTime getUpdatedTime() {
		return updatedTs;
	}
}