package com.zfgc.zfgbb.dbo;

import java.time.LocalDateTime;

public class LatestMessageInThreadViewDbo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.latest_message_in_thread_view.thread_id
     *
     * @mbg.generated Tue Oct 08 19:03:12 EDT 2024
     */
    private Integer threadId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.latest_message_in_thread_view.thread_name
     *
     * @mbg.generated Tue Oct 08 19:03:12 EDT 2024
     */
    private String threadName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.latest_message_in_thread_view.message_id
     *
     * @mbg.generated Tue Oct 08 19:03:12 EDT 2024
     */
    private Integer messageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.latest_message_in_thread_view.message_history_id
     *
     * @mbg.generated Tue Oct 08 19:03:12 EDT 2024
     */
    private Integer messageHistoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.latest_message_in_thread_view.created_ts
     *
     * @mbg.generated Tue Oct 08 19:03:12 EDT 2024
     */
    private LocalDateTime createdTs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.latest_message_in_thread_view.owner_name
     *
     * @mbg.generated Tue Oct 08 19:03:12 EDT 2024
     */
    private String ownerName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.latest_message_in_thread_view.thread_id
     *
     * @return the value of zfgbb.latest_message_in_thread_view.thread_id
     *
     * @mbg.generated Tue Oct 08 19:03:12 EDT 2024
     */
    public Integer getThreadId() {
        return threadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.latest_message_in_thread_view.thread_id
     *
     * @param threadId the value for zfgbb.latest_message_in_thread_view.thread_id
     *
     * @mbg.generated Tue Oct 08 19:03:12 EDT 2024
     */
    public void setThreadId(Integer threadId) {
        this.threadId = threadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.latest_message_in_thread_view.thread_name
     *
     * @return the value of zfgbb.latest_message_in_thread_view.thread_name
     *
     * @mbg.generated Tue Oct 08 19:03:12 EDT 2024
     */
    public String getThreadName() {
        return threadName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.latest_message_in_thread_view.thread_name
     *
     * @param threadName the value for zfgbb.latest_message_in_thread_view.thread_name
     *
     * @mbg.generated Tue Oct 08 19:03:12 EDT 2024
     */
    public void setThreadName(String threadName) {
        this.threadName = threadName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.latest_message_in_thread_view.message_id
     *
     * @return the value of zfgbb.latest_message_in_thread_view.message_id
     *
     * @mbg.generated Tue Oct 08 19:03:12 EDT 2024
     */
    public Integer getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.latest_message_in_thread_view.message_id
     *
     * @param messageId the value for zfgbb.latest_message_in_thread_view.message_id
     *
     * @mbg.generated Tue Oct 08 19:03:12 EDT 2024
     */
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.latest_message_in_thread_view.message_history_id
     *
     * @return the value of zfgbb.latest_message_in_thread_view.message_history_id
     *
     * @mbg.generated Tue Oct 08 19:03:12 EDT 2024
     */
    public Integer getMessageHistoryId() {
        return messageHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.latest_message_in_thread_view.message_history_id
     *
     * @param messageHistoryId the value for zfgbb.latest_message_in_thread_view.message_history_id
     *
     * @mbg.generated Tue Oct 08 19:03:12 EDT 2024
     */
    public void setMessageHistoryId(Integer messageHistoryId) {
        this.messageHistoryId = messageHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.latest_message_in_thread_view.created_ts
     *
     * @return the value of zfgbb.latest_message_in_thread_view.created_ts
     *
     * @mbg.generated Tue Oct 08 19:03:12 EDT 2024
     */
    public LocalDateTime getCreatedTs() {
        return createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.latest_message_in_thread_view.created_ts
     *
     * @param createdTs the value for zfgbb.latest_message_in_thread_view.created_ts
     *
     * @mbg.generated Tue Oct 08 19:03:12 EDT 2024
     */
    public void setCreatedTs(LocalDateTime createdTs) {
        this.createdTs = createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.latest_message_in_thread_view.owner_name
     *
     * @return the value of zfgbb.latest_message_in_thread_view.owner_name
     *
     * @mbg.generated Tue Oct 08 19:03:12 EDT 2024
     */
    public String getOwnerName() {
        return ownerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.latest_message_in_thread_view.owner_name
     *
     * @param ownerName the value for zfgbb.latest_message_in_thread_view.owner_name
     *
     * @mbg.generated Tue Oct 08 19:03:12 EDT 2024
     */
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName;
    }
}