package com.zfgc.zfgbb.dbo;

import java.time.LocalDate;
import java.time.LocalDateTime;

public class MessageHistoryDbo extends AbstractDbo{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.message_history.message_history_id
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	private Integer messageHistoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.message_history.message_id
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	private Integer messageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.message_history.message_text
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	private String messageText;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.message_history.current_flag
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	private Boolean currentFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.message_history.created_ts
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	private LocalDateTime createdTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.message_history.updated_ts
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	private LocalDateTime updatedTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.message_history.ip_address_id
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	private Integer ipAddressId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.message_history.message_history_id
	 * @return  the value of zfgbb.message_history.message_history_id
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public Integer getMessageHistoryId() {
		return messageHistoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.message_history.message_history_id
	 * @param messageHistoryId  the value for zfgbb.message_history.message_history_id
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public void setMessageHistoryId(Integer messageHistoryId) {
		this.messageHistoryId = messageHistoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.message_history.message_id
	 * @return  the value of zfgbb.message_history.message_id
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public Integer getMessageId() {
		return messageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.message_history.message_id
	 * @param messageId  the value for zfgbb.message_history.message_id
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.message_history.message_text
	 * @return  the value of zfgbb.message_history.message_text
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public String getMessageText() {
		return messageText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.message_history.message_text
	 * @param messageText  the value for zfgbb.message_history.message_text
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public void setMessageText(String messageText) {
		this.messageText = messageText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.message_history.current_flag
	 * @return  the value of zfgbb.message_history.current_flag
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public Boolean getCurrentFlag() {
		return currentFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.message_history.current_flag
	 * @param currentFlag  the value for zfgbb.message_history.current_flag
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public void setCurrentFlag(Boolean currentFlag) {
		this.currentFlag = currentFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.message_history.created_ts
	 * @return  the value of zfgbb.message_history.created_ts
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public LocalDateTime getCreatedTs() {
		return createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.message_history.created_ts
	 * @param createdTs  the value for zfgbb.message_history.created_ts
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public void setCreatedTs(LocalDateTime createdTs) {
		this.createdTs = createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.message_history.updated_ts
	 * @return  the value of zfgbb.message_history.updated_ts
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public LocalDateTime getUpdatedTs() {
		return updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.message_history.updated_ts
	 * @param updatedTs  the value for zfgbb.message_history.updated_ts
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public void setUpdatedTs(LocalDateTime updatedTs) {
		this.updatedTs = updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.message_history.ip_address_id
	 * @return  the value of zfgbb.message_history.ip_address_id
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public Integer getIpAddressId() {
		return ipAddressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.message_history.ip_address_id
	 * @param ipAddressId  the value for zfgbb.message_history.ip_address_id
	 * @mbg.generated  Thu Aug 22 20:55:49 EDT 2024
	 */
	public void setIpAddressId(Integer ipAddressId) {
		this.ipAddressId = ipAddressId;
	}

	@Override
	public Integer getPkId() {
		return messageHistoryId;
	}

	@Override
	public LocalDateTime getUpdatedTime() {
		return updatedTs;
	}

	@Override
	public LocalDateTime getCreatedTime() {
		return createdTs;
	}
}