package com.zfgc.zfgbb.dbo;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.time.LocalDate;

public class MessageHistoryDboExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table zfgbb.message_history
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table zfgbb.message_history
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table zfgbb.message_history
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message_history
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	public MessageHistoryDboExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message_history
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message_history
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message_history
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message_history
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message_history
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message_history
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message_history
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message_history
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message_history
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.message_history
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table zfgbb.message_history
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andMessageHistoryIdIsNull() {
			addCriterion("message_history_id is null");
			return (Criteria) this;
		}

		public Criteria andMessageHistoryIdIsNotNull() {
			addCriterion("message_history_id is not null");
			return (Criteria) this;
		}

		public Criteria andMessageHistoryIdEqualTo(Integer value) {
			addCriterion("message_history_id =", value, "messageHistoryId");
			return (Criteria) this;
		}

		public Criteria andMessageHistoryIdNotEqualTo(Integer value) {
			addCriterion("message_history_id <>", value, "messageHistoryId");
			return (Criteria) this;
		}

		public Criteria andMessageHistoryIdGreaterThan(Integer value) {
			addCriterion("message_history_id >", value, "messageHistoryId");
			return (Criteria) this;
		}

		public Criteria andMessageHistoryIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("message_history_id >=", value, "messageHistoryId");
			return (Criteria) this;
		}

		public Criteria andMessageHistoryIdLessThan(Integer value) {
			addCriterion("message_history_id <", value, "messageHistoryId");
			return (Criteria) this;
		}

		public Criteria andMessageHistoryIdLessThanOrEqualTo(Integer value) {
			addCriterion("message_history_id <=", value, "messageHistoryId");
			return (Criteria) this;
		}

		public Criteria andMessageHistoryIdIn(List<Integer> values) {
			addCriterion("message_history_id in", values, "messageHistoryId");
			return (Criteria) this;
		}

		public Criteria andMessageHistoryIdNotIn(List<Integer> values) {
			addCriterion("message_history_id not in", values, "messageHistoryId");
			return (Criteria) this;
		}

		public Criteria andMessageHistoryIdBetween(Integer value1, Integer value2) {
			addCriterion("message_history_id between", value1, value2, "messageHistoryId");
			return (Criteria) this;
		}

		public Criteria andMessageHistoryIdNotBetween(Integer value1, Integer value2) {
			addCriterion("message_history_id not between", value1, value2, "messageHistoryId");
			return (Criteria) this;
		}

		public Criteria andMessageIdIsNull() {
			addCriterion("message_id is null");
			return (Criteria) this;
		}

		public Criteria andMessageIdIsNotNull() {
			addCriterion("message_id is not null");
			return (Criteria) this;
		}

		public Criteria andMessageIdEqualTo(Integer value) {
			addCriterion("message_id =", value, "messageId");
			return (Criteria) this;
		}

		public Criteria andMessageIdNotEqualTo(Integer value) {
			addCriterion("message_id <>", value, "messageId");
			return (Criteria) this;
		}

		public Criteria andMessageIdGreaterThan(Integer value) {
			addCriterion("message_id >", value, "messageId");
			return (Criteria) this;
		}

		public Criteria andMessageIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("message_id >=", value, "messageId");
			return (Criteria) this;
		}

		public Criteria andMessageIdLessThan(Integer value) {
			addCriterion("message_id <", value, "messageId");
			return (Criteria) this;
		}

		public Criteria andMessageIdLessThanOrEqualTo(Integer value) {
			addCriterion("message_id <=", value, "messageId");
			return (Criteria) this;
		}

		public Criteria andMessageIdIn(List<Integer> values) {
			addCriterion("message_id in", values, "messageId");
			return (Criteria) this;
		}

		public Criteria andMessageIdNotIn(List<Integer> values) {
			addCriterion("message_id not in", values, "messageId");
			return (Criteria) this;
		}

		public Criteria andMessageIdBetween(Integer value1, Integer value2) {
			addCriterion("message_id between", value1, value2, "messageId");
			return (Criteria) this;
		}

		public Criteria andMessageIdNotBetween(Integer value1, Integer value2) {
			addCriterion("message_id not between", value1, value2, "messageId");
			return (Criteria) this;
		}

		public Criteria andMessageTextIsNull() {
			addCriterion("message_text is null");
			return (Criteria) this;
		}

		public Criteria andMessageTextIsNotNull() {
			addCriterion("message_text is not null");
			return (Criteria) this;
		}

		public Criteria andMessageTextEqualTo(String value) {
			addCriterion("message_text =", value, "messageText");
			return (Criteria) this;
		}

		public Criteria andMessageTextNotEqualTo(String value) {
			addCriterion("message_text <>", value, "messageText");
			return (Criteria) this;
		}

		public Criteria andMessageTextGreaterThan(String value) {
			addCriterion("message_text >", value, "messageText");
			return (Criteria) this;
		}

		public Criteria andMessageTextGreaterThanOrEqualTo(String value) {
			addCriterion("message_text >=", value, "messageText");
			return (Criteria) this;
		}

		public Criteria andMessageTextLessThan(String value) {
			addCriterion("message_text <", value, "messageText");
			return (Criteria) this;
		}

		public Criteria andMessageTextLessThanOrEqualTo(String value) {
			addCriterion("message_text <=", value, "messageText");
			return (Criteria) this;
		}

		public Criteria andMessageTextLike(String value) {
			addCriterion("message_text like", value, "messageText");
			return (Criteria) this;
		}

		public Criteria andMessageTextNotLike(String value) {
			addCriterion("message_text not like", value, "messageText");
			return (Criteria) this;
		}

		public Criteria andMessageTextIn(List<String> values) {
			addCriterion("message_text in", values, "messageText");
			return (Criteria) this;
		}

		public Criteria andMessageTextNotIn(List<String> values) {
			addCriterion("message_text not in", values, "messageText");
			return (Criteria) this;
		}

		public Criteria andMessageTextBetween(String value1, String value2) {
			addCriterion("message_text between", value1, value2, "messageText");
			return (Criteria) this;
		}

		public Criteria andMessageTextNotBetween(String value1, String value2) {
			addCriterion("message_text not between", value1, value2, "messageText");
			return (Criteria) this;
		}

		public Criteria andCreatedTsIsNull() {
			addCriterion("created_ts is null");
			return (Criteria) this;
		}

		public Criteria andCreatedTsIsNotNull() {
			addCriterion("created_ts is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedTsEqualTo(LocalDate value) {
			addCriterion("created_ts =", value, "createdTs");
			return (Criteria) this;
		}

		public Criteria andCreatedTsNotEqualTo(LocalDate value) {
			addCriterion("created_ts <>", value, "createdTs");
			return (Criteria) this;
		}

		public Criteria andCreatedTsGreaterThan(LocalDate value) {
			addCriterion("created_ts >", value, "createdTs");
			return (Criteria) this;
		}

		public Criteria andCreatedTsGreaterThanOrEqualTo(LocalDate value) {
			addCriterion("created_ts >=", value, "createdTs");
			return (Criteria) this;
		}

		public Criteria andCreatedTsLessThan(LocalDate value) {
			addCriterion("created_ts <", value, "createdTs");
			return (Criteria) this;
		}

		public Criteria andCreatedTsLessThanOrEqualTo(LocalDate value) {
			addCriterion("created_ts <=", value, "createdTs");
			return (Criteria) this;
		}

		public Criteria andCreatedTsIn(List<LocalDate> values) {
			addCriterion("created_ts in", values, "createdTs");
			return (Criteria) this;
		}

		public Criteria andCreatedTsNotIn(List<LocalDate> values) {
			addCriterion("created_ts not in", values, "createdTs");
			return (Criteria) this;
		}

		public Criteria andCreatedTsBetween(LocalDate value1, LocalDate value2) {
			addCriterion("created_ts between", value1, value2, "createdTs");
			return (Criteria) this;
		}

		public Criteria andCreatedTsNotBetween(LocalDate value1, LocalDate value2) {
			addCriterion("created_ts not between", value1, value2, "createdTs");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsIsNull() {
			addCriterion("updated_ts is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsIsNotNull() {
			addCriterion("updated_ts is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsEqualTo(LocalDate value) {
			addCriterion("updated_ts =", value, "updatedTs");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsNotEqualTo(LocalDate value) {
			addCriterion("updated_ts <>", value, "updatedTs");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsGreaterThan(LocalDate value) {
			addCriterion("updated_ts >", value, "updatedTs");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsGreaterThanOrEqualTo(LocalDate value) {
			addCriterion("updated_ts >=", value, "updatedTs");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsLessThan(LocalDate value) {
			addCriterion("updated_ts <", value, "updatedTs");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsLessThanOrEqualTo(LocalDate value) {
			addCriterion("updated_ts <=", value, "updatedTs");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsIn(List<LocalDate> values) {
			addCriterion("updated_ts in", values, "updatedTs");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsNotIn(List<LocalDate> values) {
			addCriterion("updated_ts not in", values, "updatedTs");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsBetween(LocalDate value1, LocalDate value2) {
			addCriterion("updated_ts between", value1, value2, "updatedTs");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsNotBetween(LocalDate value1, LocalDate value2) {
			addCriterion("updated_ts not between", value1, value2, "updatedTs");
			return (Criteria) this;
		}

		public Criteria andCurrentFlagIsNull() {
			addCriterion("current_flag is null");
			return (Criteria) this;
		}

		public Criteria andCurrentFlagIsNotNull() {
			addCriterion("current_flag is not null");
			return (Criteria) this;
		}

		public Criteria andCurrentFlagEqualTo(Boolean value) {
			addCriterion("current_flag =", value, "currentFlag");
			return (Criteria) this;
		}

		public Criteria andCurrentFlagNotEqualTo(Boolean value) {
			addCriterion("current_flag <>", value, "currentFlag");
			return (Criteria) this;
		}

		public Criteria andCurrentFlagGreaterThan(Boolean value) {
			addCriterion("current_flag >", value, "currentFlag");
			return (Criteria) this;
		}

		public Criteria andCurrentFlagGreaterThanOrEqualTo(Boolean value) {
			addCriterion("current_flag >=", value, "currentFlag");
			return (Criteria) this;
		}

		public Criteria andCurrentFlagLessThan(Boolean value) {
			addCriterion("current_flag <", value, "currentFlag");
			return (Criteria) this;
		}

		public Criteria andCurrentFlagLessThanOrEqualTo(Boolean value) {
			addCriterion("current_flag <=", value, "currentFlag");
			return (Criteria) this;
		}

		public Criteria andCurrentFlagIn(List<Boolean> values) {
			addCriterion("current_flag in", values, "currentFlag");
			return (Criteria) this;
		}

		public Criteria andCurrentFlagNotIn(List<Boolean> values) {
			addCriterion("current_flag not in", values, "currentFlag");
			return (Criteria) this;
		}

		public Criteria andCurrentFlagBetween(Boolean value1, Boolean value2) {
			addCriterion("current_flag between", value1, value2, "currentFlag");
			return (Criteria) this;
		}

		public Criteria andCurrentFlagNotBetween(Boolean value1, Boolean value2) {
			addCriterion("current_flag not between", value1, value2, "currentFlag");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table zfgbb.message_history
	 * @mbg.generated  Sun Apr 03 23:11:37 EDT 2022
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zfgbb.message_history
     *
     * @mbg.generated do_not_delete_during_merge Sun Feb 27 20:56:25 EST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}