package com.zfgc.zfgbb.dbo;

import java.time.LocalDateTime;

public class PollDbo extends AbstractDbo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.poll.poll_id
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    private Integer pollId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.poll.poll_question
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    private String pollQuestion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.poll.thread_id
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    private Integer threadId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.poll.created_ts
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    private LocalDateTime createdTs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.poll.updated_ts
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    private LocalDateTime updatedTs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.poll.poll_id
     *
     * @return the value of zfgbb.poll.poll_id
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public Integer getPollId() {
        return pollId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.poll.poll_id
     *
     * @param pollId the value for zfgbb.poll.poll_id
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public void setPollId(Integer pollId) {
        this.pollId = pollId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.poll.poll_question
     *
     * @return the value of zfgbb.poll.poll_question
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public String getPollQuestion() {
        return pollQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.poll.poll_question
     *
     * @param pollQuestion the value for zfgbb.poll.poll_question
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public void setPollQuestion(String pollQuestion) {
        this.pollQuestion = pollQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.poll.thread_id
     *
     * @return the value of zfgbb.poll.thread_id
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public Integer getThreadId() {
        return threadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.poll.thread_id
     *
     * @param threadId the value for zfgbb.poll.thread_id
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public void setThreadId(Integer threadId) {
        this.threadId = threadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.poll.created_ts
     *
     * @return the value of zfgbb.poll.created_ts
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public LocalDateTime getCreatedTs() {
        return createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.poll.created_ts
     *
     * @param createdTs the value for zfgbb.poll.created_ts
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public void setCreatedTs(LocalDateTime createdTs) {
        this.createdTs = createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.poll.updated_ts
     *
     * @return the value of zfgbb.poll.updated_ts
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public LocalDateTime getUpdatedTs() {
        return updatedTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.poll.updated_ts
     *
     * @param updatedTs the value for zfgbb.poll.updated_ts
     *
     * @mbg.generated Sun Sep 01 00:50:50 EDT 2024
     */
    public void setUpdatedTs(LocalDateTime updatedTs) {
        this.updatedTs = updatedTs;
    }

	@Override
	public Integer getPkId() {
		return pollId;
	}

	@Override
	public LocalDateTime getUpdatedTime() {
		return updatedTs;
	}

	@Override
	public LocalDateTime getCreatedTime() {
		return createdTs;
	}
}