package com.zfgc.zfgbb.dbo;

import java.time.LocalDate;

import com.zfgc.zfgbb.dbo.AbstractDbo;
import java.time.LocalDateTime;

public class ThreadDbo extends AbstractDbo {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.thread.thread_id
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	private Integer threadId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.thread.thread_name
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	private String threadName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.thread.locked_flag
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	private Boolean lockedFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.thread.pinned_flag
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	private Boolean pinnedFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.thread.created_ts
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	private LocalDateTime createdTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.thread.updated_ts
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	private LocalDateTime updatedTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.thread.board_id
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	private Integer boardId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.thread.created_user_id
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	private Integer createdUserId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.thread.thread_id
	 * @return  the value of zfgbb.thread.thread_id
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public Integer getThreadId() {
		return threadId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.thread.thread_id
	 * @param threadId  the value for zfgbb.thread.thread_id
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public void setThreadId(Integer threadId) {
		this.threadId = threadId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.thread.thread_name
	 * @return  the value of zfgbb.thread.thread_name
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public String getThreadName() {
		return threadName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.thread.thread_name
	 * @param threadName  the value for zfgbb.thread.thread_name
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public void setThreadName(String threadName) {
		this.threadName = threadName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.thread.locked_flag
	 * @return  the value of zfgbb.thread.locked_flag
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public Boolean getLockedFlag() {
		return lockedFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.thread.locked_flag
	 * @param lockedFlag  the value for zfgbb.thread.locked_flag
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public void setLockedFlag(Boolean lockedFlag) {
		this.lockedFlag = lockedFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.thread.pinned_flag
	 * @return  the value of zfgbb.thread.pinned_flag
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public Boolean getPinnedFlag() {
		return pinnedFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.thread.pinned_flag
	 * @param pinnedFlag  the value for zfgbb.thread.pinned_flag
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public void setPinnedFlag(Boolean pinnedFlag) {
		this.pinnedFlag = pinnedFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.thread.created_ts
	 * @return  the value of zfgbb.thread.created_ts
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public LocalDateTime getCreatedTs() {
		return createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.thread.created_ts
	 * @param createdTs  the value for zfgbb.thread.created_ts
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public void setCreatedTs(LocalDateTime createdTs) {
		this.createdTs = createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.thread.updated_ts
	 * @return  the value of zfgbb.thread.updated_ts
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public LocalDateTime getUpdatedTs() {
		return updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.thread.updated_ts
	 * @param updatedTs  the value for zfgbb.thread.updated_ts
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public void setUpdatedTs(LocalDateTime updatedTs) {
		this.updatedTs = updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.thread.board_id
	 * @return  the value of zfgbb.thread.board_id
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public Integer getBoardId() {
		return boardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.thread.board_id
	 * @param boardId  the value for zfgbb.thread.board_id
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public void setBoardId(Integer boardId) {
		this.boardId = boardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.thread.created_user_id
	 * @return  the value of zfgbb.thread.created_user_id
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public Integer getCreatedUserId() {
		return createdUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.thread.created_user_id
	 * @param createdUserId  the value for zfgbb.thread.created_user_id
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public void setCreatedUserId(Integer createdUserId) {
		this.createdUserId = createdUserId;
	}

	@Override
	public Integer getPkId() {
		return boardId;
	}

	@Override
	public LocalDateTime getUpdatedTime() {
		return updatedTs;
	}
}