package com.zfgc.zfgbb.dbo;

import java.time.LocalDate;
import java.time.LocalDateTime;

import com.zfgc.zfgbb.dao.AbstractDao;
import com.zfgc.zfgbb.dbo.AbstractDbo;

public class UserPermissionViewDbo extends AbstractDbo {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_permission_view.user_id
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_permission_view.permission_id
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	private Integer permissionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_permission_view.permission_code
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	private String permissionCode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_permission_view.user_id
	 * @return  the value of zfgbb.user_permission_view.user_id
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_permission_view.user_id
	 * @param userId  the value for zfgbb.user_permission_view.user_id
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_permission_view.permission_id
	 * @return  the value of zfgbb.user_permission_view.permission_id
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public Integer getPermissionId() {
		return permissionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_permission_view.permission_id
	 * @param permissionId  the value for zfgbb.user_permission_view.permission_id
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public void setPermissionId(Integer permissionId) {
		this.permissionId = permissionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_permission_view.permission_code
	 * @return  the value of zfgbb.user_permission_view.permission_code
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public String getPermissionCode() {
		return permissionCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_permission_view.permission_code
	 * @param permissionCode  the value for zfgbb.user_permission_view.permission_code
	 * @mbg.generated  Mon Jul 08 22:12:56 EDT 2024
	 */
	public void setPermissionCode(String permissionCode) {
		this.permissionCode = permissionCode;
	}

	@Override
	public Integer getPkId() {
		return null;
	}

	@Override
	public LocalDateTime getUpdatedTime() {
		// TODO Auto-generated method stub
		return null;
	}
}