package com.zfgc.zfgbb.dbo;

import java.time.Instant;

import com.zfgc.zfgbb.dbo.AbstractDbo;

public class UserDbo extends AbstractDbo {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user.user_id
	 * @mbg.generated  Sat Feb 26 19:52:59 EST 2022
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user.display_name
	 * @mbg.generated  Sat Feb 26 19:52:59 EST 2022
	 */
	private Object displayName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user.created_ts
	 * @mbg.generated  Sat Feb 26 19:52:59 EST 2022
	 */
	private Instant createdTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user.updated_ts
	 * @mbg.generated  Sat Feb 26 19:52:59 EST 2022
	 */
	private Instant updatedTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user.sso_key
	 * @mbg.generated  Sat Feb 26 19:52:59 EST 2022
	 */
	private String ssoKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user.active_flag
	 * @mbg.generated  Sat Feb 26 19:52:59 EST 2022
	 */
	private Boolean activeFlag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user.user_id
	 * @return  the value of zfgbb.user.user_id
	 * @mbg.generated  Sat Feb 26 19:52:59 EST 2022
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user.user_id
	 * @param userId  the value for zfgbb.user.user_id
	 * @mbg.generated  Sat Feb 26 19:52:59 EST 2022
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user.display_name
	 * @return  the value of zfgbb.user.display_name
	 * @mbg.generated  Sat Feb 26 19:52:59 EST 2022
	 */
	public Object getDisplayName() {
		return displayName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user.display_name
	 * @param displayName  the value for zfgbb.user.display_name
	 * @mbg.generated  Sat Feb 26 19:52:59 EST 2022
	 */
	public void setDisplayName(Object displayName) {
		this.displayName = displayName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user.created_ts
	 * @return  the value of zfgbb.user.created_ts
	 * @mbg.generated  Sat Feb 26 19:52:59 EST 2022
	 */
	public Instant getCreatedTs() {
		return createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user.created_ts
	 * @param createdTs  the value for zfgbb.user.created_ts
	 * @mbg.generated  Sat Feb 26 19:52:59 EST 2022
	 */
	public void setCreatedTs(Instant createdTs) {
		this.createdTs = createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user.updated_ts
	 * @return  the value of zfgbb.user.updated_ts
	 * @mbg.generated  Sat Feb 26 19:52:59 EST 2022
	 */
	public Instant getUpdatedTs() {
		return updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user.updated_ts
	 * @param updatedTs  the value for zfgbb.user.updated_ts
	 * @mbg.generated  Sat Feb 26 19:52:59 EST 2022
	 */
	public void setUpdatedTs(Instant updatedTs) {
		this.updatedTs = updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user.sso_key
	 * @return  the value of zfgbb.user.sso_key
	 * @mbg.generated  Sat Feb 26 19:52:59 EST 2022
	 */
	public String getSsoKey() {
		return ssoKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user.sso_key
	 * @param ssoKey  the value for zfgbb.user.sso_key
	 * @mbg.generated  Sat Feb 26 19:52:59 EST 2022
	 */
	public void setSsoKey(String ssoKey) {
		this.ssoKey = ssoKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user.active_flag
	 * @return  the value of zfgbb.user.active_flag
	 * @mbg.generated  Sat Feb 26 19:52:59 EST 2022
	 */
	public Boolean getActiveFlag() {
		return activeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user.active_flag
	 * @param activeFlag  the value for zfgbb.user.active_flag
	 * @mbg.generated  Sat Feb 26 19:52:59 EST 2022
	 */
	public void setActiveFlag(Boolean activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Override
	public Integer getRecordId() {
		return userId;
	}

	@Override
	public Instant getUpdatedTime() {
		return updatedTs;
	}
}