package com.zfgc.zfgbb.dbo;

import java.time.LocalDateTime;

public class UserContactInfoDbo extends AbstractDbo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_contact_info.user_id
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_contact_info.email_address_id
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	private Integer emailAddressId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_contact_info.allow_email_flag
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	private Boolean allowEmailFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_contact_info.allow_pm_flag
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	private Boolean allowPmFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_contact_info.created_ts
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	private LocalDateTime createdTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_contact_info.updated_ts
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	private LocalDateTime updatedTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_contact_info.migration_hash
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	private String migrationHash;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_contact_info.user_id
	 * @return  the value of zfgbb.user_contact_info.user_id
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_contact_info.user_id
	 * @param userId  the value for zfgbb.user_contact_info.user_id
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_contact_info.email_address_id
	 * @return  the value of zfgbb.user_contact_info.email_address_id
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	public Integer getEmailAddressId() {
		return emailAddressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_contact_info.email_address_id
	 * @param emailAddressId  the value for zfgbb.user_contact_info.email_address_id
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	public void setEmailAddressId(Integer emailAddressId) {
		this.emailAddressId = emailAddressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_contact_info.allow_email_flag
	 * @return  the value of zfgbb.user_contact_info.allow_email_flag
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	public Boolean getAllowEmailFlag() {
		return allowEmailFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_contact_info.allow_email_flag
	 * @param allowEmailFlag  the value for zfgbb.user_contact_info.allow_email_flag
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	public void setAllowEmailFlag(Boolean allowEmailFlag) {
		this.allowEmailFlag = allowEmailFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_contact_info.allow_pm_flag
	 * @return  the value of zfgbb.user_contact_info.allow_pm_flag
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	public Boolean getAllowPmFlag() {
		return allowPmFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_contact_info.allow_pm_flag
	 * @param allowPmFlag  the value for zfgbb.user_contact_info.allow_pm_flag
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	public void setAllowPmFlag(Boolean allowPmFlag) {
		this.allowPmFlag = allowPmFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_contact_info.created_ts
	 * @return  the value of zfgbb.user_contact_info.created_ts
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	public LocalDateTime getCreatedTs() {
		return createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_contact_info.created_ts
	 * @param createdTs  the value for zfgbb.user_contact_info.created_ts
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	public void setCreatedTs(LocalDateTime createdTs) {
		this.createdTs = createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_contact_info.updated_ts
	 * @return  the value of zfgbb.user_contact_info.updated_ts
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	public LocalDateTime getUpdatedTs() {
		return updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_contact_info.updated_ts
	 * @param updatedTs  the value for zfgbb.user_contact_info.updated_ts
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	public void setUpdatedTs(LocalDateTime updatedTs) {
		this.updatedTs = updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_contact_info.migration_hash
	 * @return  the value of zfgbb.user_contact_info.migration_hash
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	public String getMigrationHash() {
		return migrationHash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_contact_info.migration_hash
	 * @param migrationHash  the value for zfgbb.user_contact_info.migration_hash
	 * @mbg.generated  Sun May 18 13:28:45 EDT 2025
	 */
	public void setMigrationHash(String migrationHash) {
		this.migrationHash = migrationHash;
	}

	@Override
	public Integer getPkId() {
		return userId;
	}

	@Override
	public LocalDateTime getUpdatedTime() {
		return updatedTs;
	}

	@Override
	public LocalDateTime getCreatedTime() {
		return createdTs;
	}
} 