apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "mydb"
---
apiVersion: v1
kind: Volume
metadata:
  name: postgres-config
spec:
  configMap:
    name: postgres-config
