# base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions-runner
spec:
  replicas: 3  # Multiple runner instances
  selector:
    matchLabels:
      app: github-actions-runner
  template:
    metadata:
      labels:
        app: github-actions-runner
    spec:
      containers:
      - name: github-actions-runner
        image: ghcr.io/actions/runner:latest
        env:
        - name: RUNNER_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-actions-secrets
              key: github-token
        - name: RUNNER_LABEL
          value: $(RUNNER_LABEL)
        - name: RUNNER_NAME
          value: $(RUNNER_NAME)
        - name: RUNNER_REPO_URL
          value: $(RUNNER_REPO_URL)
        - name: GITHUB_APP_ID
          value: $(GITHUB_APP_ID)
        - name: GITHUB_INSTALLATION_ID
          value: $(GITHUB_INSTALLATION_ID)
        - name: GITHUB_APP_PRIVATE_KEY_PATH
          value: $(GITHUB_APP_PRIVATE_KEY_PATH)
        volumeMounts:
        - name: github-app-key
          mountPath: /etc/github-app
          readOnly: true
        - mountPath: /tmp/github-runner
          name: runner-workdir
      volumes:
      - name: github-app-key
        secret:
          secretName: github-app-secret
      - name: runner-workdir
        emptyDir: {}
