apiVersion: v1
kind: Service
metadata:
  name: github-actions-runner-service
spec:
  selector:
    app: github-actions-runner
  ports:
    - protocol: TCP
      port: 80      # Exposes port 80 externally (Stable port to interact with the runner)
      targetPort: 8080  
  type: ClusterIP 
