namespace: zfgbb-develop
resources:
- namespace.yml
- ../../base
- ../../services/zfgbb

configMapGenerator:
- behavior: merge
  envs:
  - .env
  name: old-skool-config
- behavior: merge
  envs:
  - .env
  name: zfgbb-config

secretGenerator:
- behavior: merge
  envs:
  - .env
  name: old-skool-secrets
  type: Opaque
- behavior: merge
  envs:
  - .env.secret
  name: zfgbb-secrets
  type: Opaque

# replacements:
#   - source:
#       kind: Deployment
#       name: postgres
#       # We want to replace the host path with the actual path
#       fieldPath: spec.template.spec.volumes[?(@.name=="postgres-vol")].hostPath.path
#     targets:
#       - select:
#           kind: Deployment
#           name: zfgbb
#         fieldPaths:
#           - spec.template.spec.containers[?(@.name=="postgres")].volumeMounts[?(@.name=="postgres-vol")].mountPath

# replacements:
# - source:
#     fieldPath: data.NAMESPACE
#     kind: ConfigMap
#     name: old-skool-config
#   targets:
#   - fieldPaths:
#     - metadata.namespace
#     select:
#       name: zfgbb
# - source:
#     fieldPath: data.NAMESPACE
#     kind: ConfigMap
#     name: zfgbb-config
#   targets:
#   - fieldPaths:
#     - metadata.name
#     select:
#       kind: Namespace
#      # name: zfgbb

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
