namespace: zfgbb-develop

resources:
- namespace.yml
- ../../base
- ../../services/zfgbb

configMapGenerator:
- behavior: merge
  envs:
  - .env
  name: old-skool-config
- behavior: merge
  envs:
  - .env
  name: zfgbb-config

secretGenerator:
- behavior: merge
  envs:
  - .env
  name: old-skool-secrets
  type: Opaque
- behavior: merge
  envs:
  - .env.secret
  name: zfgbb-secrets
  type: Opaque

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
