namespace: $(NAMESPACE)
resources:
  - apache-deployment.yaml
  - mysql-deployment.yaml
  - postgres-deployment.yaml
  - zfg-bb-deployment.yaml
  - ingress.yaml

configMapGenerator:
  - name: old-skool-config
    files:
      - .env
  - name: zfg-bb-config
    files:
      - .env

secretGenerator:
  - name: old-skool-secrets
    literals:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  - name: zfg-bb-secrets
    literals:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}