apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zfgbb-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-vol
      volumes:
      - name: postgres-vol
        hostPath:
          path: "${POSTGRES_DIRECTORY}"
          type: DirectoryOrCreate