---
- hosts: chiaria_octavia
  become: yes
  tasks:
    - name: Install Docker
      apt: docker.io
      state: present

    - name: Install kube cli utilities
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - kubectl
        - kubeadm
        - kubelet
    - name: Initialize Kubernetes Cluster
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      register: kubeadm_init

    - name: Copy kubeconfig to host
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: ./kubeconfig
        flat: yes

    - name: Copy kube config to host
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: ./kubeconfig
        flat: yes

- hosts: chiaria_octavia
  become: yes
  tasks:
    - name: Install Kubernetes packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - kubeadm
        - kubectl
        - kubelet
        - kubernetes-cni

    - name: Copy kubeconfig to host
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: ./kubeconfig    
    - name: Join worker nodes
      command: "${{ hostvars['chiara_octavia']['kubeadm_init']['stdout_lines'][0]}}"
      when: "'kubeadm join' in hostvars['chiara_octavia']['kubeadm_init']['stdout']"