package com.zfgc.zfgbb.dbo.zfgbb;

import java.time.Instant;

import com.zfgc.zfgbb.dbo.AbstractDbo;

public class UserDbo extends AbstractDbo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.user.user_id
     *
     * @mbg.generated Thu Feb 24 23:49:20 EST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.user.display_name
     *
     * @mbg.generated Thu Feb 24 23:49:20 EST 2022
     */
    private Object displayName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.user.created_ts
     *
     * @mbg.generated Thu Feb 24 23:49:20 EST 2022
     */
    private Instant createdTs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.user.updated_ts
     *
     * @mbg.generated Thu Feb 24 23:49:20 EST 2022
     */
    private Instant updatedTs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.user.user_id
     *
     * @return the value of zfgbb.user.user_id
     *
     * @mbg.generated Thu Feb 24 23:49:20 EST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.user.user_id
     *
     * @param userId the value for zfgbb.user.user_id
     *
     * @mbg.generated Thu Feb 24 23:49:20 EST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.user.display_name
     *
     * @return the value of zfgbb.user.display_name
     *
     * @mbg.generated Thu Feb 24 23:49:20 EST 2022
     */
    public Object getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.user.display_name
     *
     * @param displayName the value for zfgbb.user.display_name
     *
     * @mbg.generated Thu Feb 24 23:49:20 EST 2022
     */
    public void setDisplayName(Object displayName) {
        this.displayName = displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.user.created_ts
     *
     * @return the value of zfgbb.user.created_ts
     *
     * @mbg.generated Thu Feb 24 23:49:20 EST 2022
     */
    public Instant getCreatedTs() {
        return createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.user.created_ts
     *
     * @param createdTs the value for zfgbb.user.created_ts
     *
     * @mbg.generated Thu Feb 24 23:49:20 EST 2022
     */
    public void setCreatedTs(Instant createdTs) {
        this.createdTs = createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.user.updated_ts
     *
     * @return the value of zfgbb.user.updated_ts
     *
     * @mbg.generated Thu Feb 24 23:49:20 EST 2022
     */
    public Instant getUpdatedTs() {
        return updatedTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.user.updated_ts
     *
     * @param updatedTs the value for zfgbb.user.updated_ts
     *
     * @mbg.generated Thu Feb 24 23:49:20 EST 2022
     */
    public void setUpdatedTs(Instant updatedTs) {
        this.updatedTs = updatedTs;
    }

	@Override
	public Integer getRecordId() {
		return userId;
	}

	@Override
	public Instant getUpdatedTime() {
		return updatedTs;
	}
}