apiVersion: apps/v1
kind: Deployment
metadata:
  name: old-skool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: old-skool
  template:
    metadata:
      labels:
        app: old-skool
    spec:
      containers:
        - name: apache
          image: "httpd:latest"
          volumeMounts:
            - name: apache-content
              mountPath: /usr/local/apache2/htdocs
            - name: vhost-config
              mountPath: /usr/local/apache2/conf/extra
        - name: mysql
          image: "mysql:5.7"
          envFrom:
            - secretRef:
                name: old-skool-secrets
      volumes:
        - name: apache-content
          hostPath:
            path: ${APACHE_DIRECTORY}
            type: DirectoryOrCreate
        - name: vhost-config
          hostPath:
            path: ${APACHE_VHOST_CONFIG_DIRECTORY}
            type: DirectoryOrCreate
