# name: Kubernetes Deployment

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Kubernetes CLI
#       uses: azure/setup-kubectl@v1
#       with:
#         version: 'v1.21.0'
#     - name: Create MySQL and PostgreSQL Secrets
#       run: |
#         echo "$MYSQL_PASSWORD" | base64 | kubectl create secret generic mysql-secret \
#           --from-literal=password=- \
#           --dry-run=client -o yaml | kubectl apply -f -
#         echo "$POSTGRES_PASSWORD" | base64 | kubectl create secret generic postgres-secret \
#           --from-literal=password=- \
#           --dry-run=client -o yaml | kubectl apply -f -
#       env:
#         MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
#         POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
#     - name: Deploy
#       run: |
#         export $(cat kustomize.env | xargs) # Load and export env vars
#         kustomize build base | kubectl apply -f -